name: Grammar Issue
description: "Report spelling, grammar, and formatting mistakes."
title: "[Grammar Error]: "
labels: [grammar]
body:
  - type: input
    attributes:
      label: Article Title & Path
      description: Where is the error located?
      placeholder: "Example: 'content/Encyclopedia Mysenvaria/History/Biographies/Jack Black'"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problematic Text
      description: Copy and paste the line(s) with the issue.
      placeholder: "\"Jack Black is a really bad guy\""
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested Fix
      description: How should the text be changed or corrected?
      placeholder: "The text should read, \"Jack Black is a really awesome guy\""
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Submission Agreement
      options:
      - label: "By checking this box you confirm that you have read and agree to the Encyclopedia Mysenvaria's [Contribution Policy](https://github.com/RagtimeGal/quartz--encyclopedia-mysenvaria?tab=contributing-ov-file#readme), and grant the Project a perpetual, irrevocable, royalty-free license to use, edit, and integrate your submission into the project."
        required: true
