name: Article Suggestion
description: "Make a suggestion to improve an article."
title: "[Suggestion]: "
labels: [sugestion]
body:
  - type: input
    attributes:
      label: Article Title & Path
      description: What article are you making a suggestion for?
      placeholder: "Example: 'content/Encyclopedia Mysenvaria/Geography/Natural Features/Your Mother'"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggestion
      description: What in the article could use improving, and how would you improve it?
      placeholder: "The article mentions that Your Mother is large, but has no mention of her actual size. It should clearly state her girth."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Submission Agreement
      options:
      - label: "By checking this box you confirm that you have read and agree to the Encyclopedia Mysenvaria's [Contribution Policy](https://github.com/RagtimeGal/quartz--encyclopedia-mysenvaria?tab=contributing-ov-file#readme), and grant the Project a perpetual, irrevocable, royalty-free license to use, edit, and integrate your submission into the project."
        required: true
