%%{init: { 'logLevel': 'debug', 'theme': 'neutral' } }%%
timeline
    -651 : The God War Era
    0 : Post-War Era
    609 : Golden Era
    1214 : Modern Era
    0 : Harmonic Treaty Signed
    -690 : First Gods Created
    1496 : Distress Signal Sent
    1214 : Printing Press Invented
    -651 : First God Dies
    296 : civil uprest
    920 : lots of inventions
    -273 : End War Epoch
    -523 : Mid War Epoch
    1336 : colonization
    -651 : Early War Epoch
    -523 : Plants Invented
    -273 : First Womb-God Born
    1309 : Guns Invented
    34 : Founding of Eastern Postciv
    42 : Founding of Eastern Mediciv
    18 : Founding of Southern Tearciv
    43 : Founding of Western Mediciv
    68 : Fouding of Jungle Deltown
    64 : Founding of Inner Rainciv
    575 : lots of philosophical and ethical changes in societies
    -523 : Iteration Period
    -527 : First God Council Held
    -426 : Dwarves Created
    -421 : Elves Created
    -388 : First Demi-God Born
    -336 : First Construct Created
    -336 : World Flooded
    -587 : Great Oceanic Crater Created
    -286 : Northern Mountains Created
    -161 : Eastern Archipelago Created
    -118 : Southern Craters Created
    -37 : Great Tear Created
    -69 : First Demi-God Dies
    -306 : First Elven Elder
    -37 : First Elven Elder Passes
    -419 : Founding of Sextown
    -440 : Creations Act Passed
    -440 : Second God Council Held
    -442 : Humanity Created
    -498 : Animals Invented
    -476 : First Organism of Mass Destruction Invented
    -485 : Octopus Invented
    -494 : Crabs Invented
    -489 : Amphibians Invented
    -481 : Dimetrodon Invented
    -462 : Mammals Invented
    -475 : Reptilia Invented
    -443 : Birds Invented
    1313 : Academy Publishing Company founded
    1393 : Second Edition Encyclopedia Mysenvaria published
