### THIS CODE WAS GENERATED BY AN LLM!
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
featured_block_generator.py

* Scans every markdown file under the vault’s CONTENT_DIR (default: “content”).
* Looks for a front‑matter key called **featured_data**.
* Extracts the description, image and a list of “fun fact” keys.
* Resolves those keys against the `%%`‑section that follows the markdown body.
* Writes a JSON report (all extracted pages) to
  content/Meta/Programs/debug/featured_block_generator/extracted_featured.json
* Rewrites the first call‑out box in `_index.md` with a block that shows
  a *randomly chosen* featured article **that actually has a description**, and
  a random selection of fun‑facts taken from **all** pages that contain
  `featured_data`.
* Supports a dry‑run mode (`DRY_RUN=True`) where nothing is written.
"""

# ----------------------------------------------------------------------
# 1️⃣ CONFIGURATION
# ----------------------------------------------------------------------
import os
import re
import json
import pathlib
import sys
import random
from collections import defaultdict
from typing import Any, Dict, List, Tuple, Optional

CONTENT_DIRNAME = "content"

# Debug artefacts live inside the vault (under content/)
DERIVED_DIR_REL = pathlib.Path(
    "Meta/Programs/debug/featured_block_generator"
)

EXTRACTED_JSON = "extracted_featured.json"
WARNINGS_MD = "featured_warnings.txt"
DRY_RUN = False            # set True for “check only”

EXCLUDE_DIRS = {
    ".git", ".github", ".obsidian", ".quartz", "public",
    "node_modules", ".vitepress", ".docusaurus", "dist", "build"
}

ENV_CONTENT_ROOT = os.getenv("FEATURED_CONTENT_ROOT")

MAX_FUN_FACTS = 5           # how many facts to show in the call‑out


# ----------------------------------------------------------------------
# 2️⃣ ROOT DISCOVERY
# ----------------------------------------------------------------------
def find_content_root() -> pathlib.Path:
    """Return the absolute Path that contains the markdown vault."""
    if ENV_CONTENT_ROOT:
        p = pathlib.Path(ENV_CONTENT_ROOT)
        print(f"[ROOT] Using ENV FEATURED_CONTENT_ROOT = {p}")
        return p

    candidates: List[pathlib.Path] = []
    ws = os.getenv("GITHUB_WORKSPACE")
    if ws:
        candidates.append(pathlib.Path(ws))
    here = pathlib.Path(__file__).resolve()
    candidates.extend(here.parents)
    candidates.append(pathlib.Path.cwd())

    for base in candidates:
        p = base / CONTENT_DIRNAME
        if p.is_dir():
            print(f"[ROOT] Discovered content root: {p}")
            return p

    fallback = here.parent / CONTENT_DIRNAME
    print(f"[ROOT] Fallback content root: {fallback}")
    return fallback


# ----------------------------------------------------------------------
# 3️⃣ MARKDOWN DISCOVERY
# ----------------------------------------------------------------------
def iter_markdown(root: pathlib.Path):
    """Yield every *.md file under *root*, skipping the black‑list."""
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS]
        for fname in filenames:
            if fname.lower().endswith(".md"):
                yield pathlib.Path(dirpath) / fname


# ----------------------------------------------------------------------
# 4️⃣ FRONT‑MATTER HELPERS
# ----------------------------------------------------------------------
FM_RE = re.compile(r"^---\r?\n(.*?)(?:\r?\n)---\r?\n?", re.S)


def try_load_yaml(text: str) -> Optional[Dict[str, Any]]:
    try:
        import yaml  # type: ignore
    except Exception:
        return None
    try:
        data = yaml.safe_load(text)
        return data if isinstance(data, dict) else None
    except Exception:
        return None


def fallback_parse_yaml(text: str) -> Optional[Dict[str, Any]]:
    """Very tolerant YAML‑ish parser – sufficient for our simple front‑matter."""
    lines = text.splitlines()
    norm = [re.sub(r"^\t+", lambda m: "  " * len(m.group(0)), ln) for ln in lines]
    i = 0

    def cast_scalar(s: str) -> Any:
        s = s.strip()
        if (s.startswith('"') and s.endswith('"')) or (s.startswith("'") and s.endswith("'")):
            s = s[1:-1]
        if s.lower() == "true":
            return True
        if s.lower() == "false":
            return False
        if s.startswith("[") and s.endswith("]"):
            inner = s[1:-1].strip()
            if not inner:
                return []
            return [cast_scalar(p) for p in inner.split(",")]
        try:
            if "." in s:
                return float(s)
            return int(s)
        except Exception:
            return s

    def parse_block(indent: int) -> Any:
        nonlocal i
        mode = None
        obj: Dict[str, Any] = {}
        arr: List[Any] = []

        while i < len(norm):
            line = norm[i]
            if not line.strip():
                i += 1
                continue
            cur_indent = len(line) - len(line.lstrip(" "))
            if cur_indent < indent:
                break
            if cur_indent > indent:
                if mode == "list" and arr:
                    arr[-1] = parse_block(cur_indent)
                elif mode == "dict" and obj:
                    last_key = list(obj.keys())[-1]
                    obj[last_key] = parse_block(cur_indent)
                else:
                    break
                continue
            content = line[indent:]
            if content.startswith("- "):
                mode = "list"
                val = content[2:].strip()
                arr.append(cast_scalar(val) if val else {})
                i += 1
            else:
                if ":" in content:
                    mode = "dict"
                    k, v = content.split(":", 1)
                    obj[k.strip()] = cast_scalar(v) if v.strip() else {}
                    i += 1
                else:
                    break
        return arr if mode == "list" else obj

    root: Dict[str, Any] = {}
    while i < len(norm):
        line = norm[i]
        if not line.strip():
            i += 1
            continue
        if ":" in line:
            k, v = line.split(":", 1)
            key, val = k.strip(), v.strip()
            i += 1
            if val == "":
                indent = len(line) - len(line.lstrip(" ")) + 2
                root[key] = parse_block(indent)
            else:
                root[key] = cast_scalar(val)
        else:
            i += 1
    return root if root else None


def read_front_matter(md_path: pathlib.Path) -> Tuple[Optional[Dict[str, Any]], str, str]:
    """Return (front‑matter dict or None, body text, loader used)."""
    text = md_path.read_text(encoding="utf-8", errors="ignore")
    m = FM_RE.match(text)
    body = text[m.end():] if m else text
    fm_raw = m.group(1) if m else ""
    data = try_load_yaml(fm_raw)
    used = "pyyaml" if data is not None else "fallback"
    if data is None and fm_raw:
        data = fallback_parse_yaml(fm_raw)
    return (data if isinstance(data, dict) else None), body, used


# ----------------------------------------------------------------------
# 5️⃣ %%‑SECTION HELPERS
# ----------------------------------------------------------------------
def split_definitions_section(md_text: str) -> Tuple[str, Dict[str, str]]:
    """
    Everything after the first `%%` line is interpreted as a simple
    `key: value` map.
    Returns (body_without_definitions, {key: value, …})
    """
    parts = md_text.split("%%")
    if len(parts) < 2:
        return md_text, {}
    defs_raw = parts[1]
    body = parts[0]
    defs: Dict[str, str] = {}
    for line in defs_raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, val = line.split(":", 1)
        defs[key.strip()] = val.strip()
    return body, defs


# ----------------------------------------------------------------------
# 6️⃣ PAGE‑LEVEL EXTRACTION
# ----------------------------------------------------------------------
def resolve_featured_entry(raw_entry: Any, definitions: Dict[str, str]) -> Any:
    """Resolve a scalar or list entry against the definitions map."""
    if isinstance(raw_entry, list):
        return [resolve_featured_entry(e, definitions) for e in raw_entry]

    if isinstance(raw_entry, str):
        return definitions.get(raw_entry, raw_entry)

    return raw_entry


def extract_featured_from_page(md_path: pathlib.Path,
                              root: pathlib.Path) -> Optional[Dict[str, Any]]:
    """
    Return a dict with the extracted data for a page that contains
    `featured_data` in its front‑matter, or None if the key is missing.
    The dict always contains the keys:
        - src_rel
        - title
        - featured_desc
        - featured_image
        - fun_facts (list)
    """
    fm, body, _ = read_front_matter(md_path)
    if not fm or "featured_data" not in fm:
        return None

    featured_raw = fm["featured_data"]
    if not isinstance(featured_raw, dict):
        return None

    # Resolve definitions from the %% block
    _, definitions = split_definitions_section(body)

    desc_key = featured_raw.get("featured_desc")
    img_key  = featured_raw.get("featured_image")
    facts_raw = featured_raw.get("fun_facts", [])

    resolved_desc   = resolve_featured_entry(desc_key, definitions)
    resolved_img    = resolve_featured_entry(img_key, definitions)
    resolved_facts  = resolve_featured_entry(facts_raw, definitions)

    # Normalise fun_facts to a list of strings
    if isinstance(resolved_facts, list):
        fun_facts = [str(f) for f in resolved_facts]
    else:
        fun_facts = [str(resolved_facts)]

    # Title for the JSON report (front‑matter title if present, else filename)
    title = fm.get("title")
    if isinstance(title, str) and title.strip():
        title = title.strip()
    else:
        title = md_path.stem

    rel_path = md_path.relative_to(root).as_posix()

    return {
        "src_rel": rel_path,
        "title": title,
        "featured_desc": resolved_desc,
        "featured_image": resolved_img,
        "fun_facts": fun_facts,
    }


# ----------------------------------------------------------------------
# 7️⃣ JSON REPORT
# ----------------------------------------------------------------------
def write_json_report(derived_dir: pathlib.Path,
                      data: List[Dict[str, Any]],
                      warnings: List[str]) -> None:
    """Write the JSON report and a markdown warnings file."""
    derived_dir.mkdir(parents=True, exist_ok=True)

    report_path = derived_dir / EXTRACTED_JSON
    warn_path   = derived_dir / WARNINGS_MD

    report = {
        "meta": {
            "total_pages_scanned": len(data),
            "featured_pages_found": len(data),
            "warnings": len(warnings),
        },
        "featured_pages": data,
    }

    if DRY_RUN:
        print("[DRY] Would write JSON report to:", report_path)
    else:
        report_path.write_text(
            json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        print("[WROTE] JSON report ->", report_path)

    warning_lines = ["# Featured Block Generator Warnings", ""]
    if warnings:
        warning_lines.append("## Issues detected")
        warning_lines.extend(warnings)
    else:
        warning_lines.append("_No warnings_")
    warning_text = "\n".join(warning_lines)

    if DRY_RUN:
        print("[DRY] Would write warnings to:", warn_path)
    else:
        warn_path.write_text(warning_text, encoding="utf-8")
        print("[WROTE] Warnings ->", warn_path)


# ----------------------------------------------------------------------
# 8️⃣ REPLACE FIRST CALL‑OUT ON _index.md
# ----------------------------------------------------------------------
CALL_OUT_START_RE = re.compile(r"^> \[!")


def replace_first_callout(lines: List[str],
                         new_block: List[str]) -> Tuple[List[str], bool]:
    """
    Replace only the *first* call‑out block (the one that starts with `> [!`).
    Returns the new list of lines and a flag indicating whether a change was made.
    """
    start = None
    end   = None

    for i, ln in enumerate(lines):
        if CALL_OUT_START_RE.match(ln):
            start = i
            j = i + 1
            while j < len(lines):
                cur = lines[j]
                if cur.strip() == "":
                    j += 1
                    continue
                if CALL_OUT_START_RE.match(cur):
                    break          # another call‑out → stop
                if cur.startswith(">"):
                    j += 1
                    continue
                break                # non‑`>` line → end of block
            end = j
            break                     # only the first call‑out is replaced

    if start is None:
        return lines, False          # no call‑out found

    old_block = lines[start:end]
    if old_block == new_block:      # already up‑to‑date
        return lines, False

    new_lines = lines[:start] + new_block + lines[end:]
    return new_lines, True


# ----------------------------------------------------------------------
# 9️⃣ RENDER CALL‑OUT BLOCK
# ----------------------------------------------------------------------
def render_featured_block(featured: Dict[str, Any],
                         facts: List[str],
                         max_facts: int = MAX_FUN_FACTS) -> List[str]:
    """
    Build the markdown lines for the call‑out.
    * `featured` contains the description and the optional image.
    * `facts` is the *already shuffled* list of all fun‑facts from the vault.
    """
    # Description – we know the chosen page is guaranteed to have one.
    desc = str(featured.get("featured_desc", ""))

    # Image – optional.  If missing/None/empty we simply omit the line.
    raw_img = featured.get("featured_image")
    img = str(raw_img).strip() if isinstance(raw_img, str) else ""
    # If the resolved value is something other than a string (e.g. None),
    # treat it as missing.
    if not img:
        img = ""  # ensure we have a plain empty string

    chosen_facts = facts[:max_facts]

    out: List[str] = [
        "> [!tip] Featured Article & Fun Facts",
        "> > [!note] Featured Article",
        "> > ",
        f"> > {desc}",
    ]

    # Only add the image line when we actually have an image value.
    if img:
        out.append(f"> > {img}")

    out.extend([
        ">",                                   # blank line between sections
        "> > [!info] Did you know...",
    ])

    for f in chosen_facts:
        out.append(f"> > - {f}")

    out.append("")   # final blank line
    return out


# ----------------------------------------------------------------------
# 10️⃣ MAIN DRIVER
# ----------------------------------------------------------------------
def main() -> None:
    root = find_content_root()
    all_pages: List[Dict[str, Any]] = []   # every page that has featured_data
    warnings: List[str] = []

    # --------------------------------------------------------------
    # Scan the vault and collect data
    # --------------------------------------------------------------
    md_files = list(iter_markdown(root))
    print(f"[SCAN] Found {len(md_files)} markdown files under {root}")

    for md in md_files:
        try:
            entry = extract_featured_from_page(md, root)
            if entry:
                all_pages.append(entry)
        except Exception as exc:
            rel = md.relative_to(root).as_posix()
            warnings.append(f"- Error processing {rel}: {exc}")

    # --------------------------------------------------------------
    # Write JSON report & warnings (inside content/Meta/...)
    # --------------------------------------------------------------
    derived_dir_abs = root / DERIVED_DIR_REL
    write_json_report(derived_dir_abs, all_pages, warnings)

    if not all_pages:
        print("[INFO] No pages with `featured_data` – nothing to update.")
        return

    # --------------------------------------------------------------
    # Build the GLOBAL fun‑fact pool (includes every page)
    # --------------------------------------------------------------
    global_facts: List[str] = []
    for p in all_pages:
        global_facts.extend(p.get("fun_facts", []))

    random.shuffle(global_facts)

    # --------------------------------------------------------------
    # FILTER pages that are eligible to be the *featured article*.
    # They must have a non‑empty description.
    # --------------------------------------------------------------
    eligible = [
        p for p in all_pages
        if isinstance(p.get("featured_desc"), str) and p["featured_desc"].strip()
    ]

    if not eligible:
        warnings.append(
            "- No page with a valid `featured_desc` found. "
            "Cannot render a featured article."
        )
        print("[WARN] No eligible featured article – skipping home‑page update.")
    else:
        # --------------------------------------------------------------
        # Choose ONE page at random from the eligible set
        # --------------------------------------------------------------
        featured_entry = random.choice(eligible)

        # --------------------------------------------------------------
        # Load the home page and replace its first call‑out
        # --------------------------------------------------------------
        home_path = root / "_index.md"
        if not home_path.is_file():
            warnings.append("- Home page `_index.md` not found.")
            print("[WARN] Home page not found – aborting.")
        else:
            raw_home = home_path.read_text(encoding="utf-8")
            home_lines = raw_home.splitlines()

            new_block = render_featured_block(
                featured=featured_entry,
                facts=global_facts,
                max_facts=MAX_FUN_FACTS,
            )

            new_home_lines, changed = replace_first_callout(home_lines, new_block)

            if not changed:
                print("[SKIP] Call‑out on home page already up‑to‑date.")
            else:
                new_home_text = "\n".join(new_home_lines).rstrip() + "\n"
                if DRY_RUN:
                    print("[DRY] Would write updated home page.")
                else:
                    home_path.write_text(new_home_text, encoding="utf-8")
                    print("[WROTE] Updated home page ->", home_path)

    # --------------------------------------------------------------
    # Final summary
    # --------------------------------------------------------------
    print("\n=== Summary ===")
    print(f"Pages with featured_data : {len(all_pages)}")
    print(f"Eligible featured pages   : {len(eligible)}")
    print(f"Warnings generated        : {len(warnings)}")
    if warnings:
        print("\nWarnings:")
        for w in warnings:
            print(w)


if __name__ == "__main__":
    main()
