### A PORTION OF, OR ALL OF, THE CODE CONTAINED WITHIN THIS FILE WAS GENERATED BY AN LLM.
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.widgets import Slider, Button, TextBox

## Define parameters
plane_radius = 8757.84
treaty_radius = 0.53 * plane_radius
# Fixed inclination at 7.25 degrees
fixed_inclination = np.radians(7.25)
treaty_height, treaty_eccentricity = 3844, 0.11
years_per_rotation, total_days_in_year, minutes_in_day = 2, 360, 24 * 60
start_day, start_year = 0, 0

# Persistent State
state = {
    "current_frame": 0,
    "speed": 1.0,
    "paused": False,
    "rotation_enabled": True,
    "seasonal_semicircle": False,
    "view_direction": "South"
}

# Calc constants
R = np.sqrt(0.27 * plane_radius**2 + treaty_height**2)
theta = np.linspace(0, 2 * np.pi, 1000)
plane_x_circumference = plane_radius * np.cos(theta)
plane_y_circumference = plane_radius * np.sin(theta)

## Initialize the plots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 9))
plt.subplots_adjust(bottom=0.25)

# Try to maximize window
try:
    figManager = plt.get_current_fig_manager()
    figManager.window.state('zoomed')
except:
    pass

# --- UI Elements ---
ax_speed = plt.axes([0.05, 0.05, 0.05, 0.04])
txt_speed = TextBox(ax_speed, 'Speed: ', initial="1.0")

ax_day = plt.axes([0.14, 0.05, 0.05, 0.04])
txt_day = TextBox(ax_day, 'Day: ', initial="1")

ax_toggle_rot = plt.axes([0.23, 0.05, 0.1, 0.04])
btn_toggle_rot = Button(ax_toggle_rot, 'Rotation: ON')

ax_toggle_sea = plt.axes([0.34, 0.05, 0.12, 0.04])
btn_toggle_sea = Button(ax_toggle_sea, 'Seasons: OFF')

ax_view = plt.axes([0.47, 0.05, 0.12, 0.04])
btn_view = Button(ax_view, f'View: {state["view_direction"]}')

ax_pause = plt.axes([0.61, 0.05, 0.08, 0.04])
btn_pause = Button(ax_pause, 'Pause')

def set_limits_labels(ax, title, xlabel, ylabel, legend_location='best'):
    ax.set_xlim(-plane_radius * 1.3, plane_radius * 1.3)
    ax.set_ylim(-plane_radius * 1.3, plane_radius * 1.3)
    ax.set_aspect('equal', adjustable='box')
    ax.legend(loc=legend_location, fontsize='small')
    ax.set_title(title)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.grid(True, alpha=0.3)

# Top-down view components
extent_of_plane, = ax1.plot(plane_x_circumference, plane_y_circumference, color='blue', label="Extent of Plane", alpha=0.5)
orbit_line_top_down, = ax1.plot([], [], color='red', label="Treaty's Orbit", linewidth=1)
point_top_down, = ax1.plot([], [], 'o', color='gold', markersize=8, label="Harmonic Treaty", zorder=10)
apsis_dot_top, = ax1.plot([], [], 'o', color='red', markersize=4, label="Apsis", zorder=11)
influence_circle, = ax1.plot([], [], '--', color='orange', label="Area of Influence", zorder=8)
influence_fill_top = ax1.fill([], [], color='yellow', alpha=0.2, zorder=7)[0]
seasonal_line_top, = ax1.plot([], [], color='black', linestyle=':', linewidth=2, label="Seasonal Divide")

day_text_top_down = ax1.text(0.05, 0.95, '', transform=ax1.transAxes, fontsize=11, verticalalignment='top', bbox=dict(facecolor='white', alpha=0.7), zorder=20)

# Cardinal Labels for Top-Down
ax1.text(0, plane_radius * 1.15, 'NORTH', ha='center', fontweight='bold', color='blue')
ax1.text(0, -plane_radius * 1.25, 'SOUTH', ha='center', fontweight='bold', color='blue')
ax1.text(plane_radius * 1.1, 0, 'EAST', va='center', fontweight='bold', color='blue')
ax1.text(-plane_radius * 1.25, 0, 'WEST', va='center', fontweight='bold', color='blue')

set_limits_labels(ax1, "Top-Down View", "West <-> East", "South <-> North", 'lower left')

# Side view components
ax2.plot(np.linspace(-plane_radius, plane_radius, 100), np.zeros(100), color='blue', label="Plane", linewidth=2)
orbit_center_side, = ax2.plot([], [], 'o', color='red', label="Orbit Center")
orbit_line_side_view, = ax2.plot([], [], color='red', label="Treaty's Orbit", alpha=0.6)
point_side_view, = ax2.plot([], [], 'o', color='gold', markersize=8, label="Harmonic Treaty", zorder=10)
apsis_dot_side, = ax2.plot([], [], 'o', color='red', markersize=4, zorder=11)
influence_sphere_side, = ax2.plot([], [], '--', color='orange', label="Area of Influence", zorder=8)
influence_fill_side = ax2.fill([], [], color='yellow', alpha=0.2, zorder=7)[0]

angle_text_side = ax2.text(0.05, 0.95, '', transform=ax2.transAxes, fontsize=11, verticalalignment='top', bbox=dict(facecolor='white', alpha=0.7), zorder=20)
set_limits_labels(ax2, "Side View", "Lateral Profile", "Altitude (Z)")

fills = []

def refresh_graph():
    if state["paused"]:
        update(0, force_render=True)
        fig.canvas.draw_idle()

# --- Interactive Callbacks ---
def update_speed(text):
    try:
        val = float(text)
        state["speed"] = val
        refresh_graph()
    except ValueError: pass

def jump_to_day(text):
    try:
        target_day = float(text) - 1
        state["current_frame"] = target_day * minutes_in_day
        refresh_graph()
    except ValueError: pass

def toggle_pause(event):
    state["paused"] = not state["paused"]
    btn_pause.label.set_text('Resume' if state["paused"] else 'Pause')

def toggle_rotation(event):
    state["rotation_enabled"] = not state["rotation_enabled"]
    btn_toggle_rot.label.set_text(f'Rotation: {"ON" if state["rotation_enabled"] else "OFF"}')
    refresh_graph()

def toggle_seasonal(event):
    state["seasonal_semicircle"] = not state["seasonal_semicircle"]
    btn_toggle_sea.label.set_text(f'Seasons: {"ON" if state["seasonal_semicircle"] else "OFF"}')
    refresh_graph()

def cycle_view(event):
    dirs = ["South", "West", "North", "East"]
    current_idx = dirs.index(state["view_direction"])
    state["view_direction"] = dirs[(current_idx + 1) % 4]
    btn_view.label.set_text(f'View: {state["view_direction"]}')
    refresh_graph()

txt_speed.on_submit(update_speed)
txt_day.on_submit(jump_to_day)
btn_pause.on_clicked(toggle_pause)
btn_toggle_rot.on_clicked(toggle_rotation)
btn_toggle_sea.on_clicked(toggle_seasonal)
btn_view.on_clicked(cycle_view)

## Animation Logic
def update(frame, force_render=False):
    global fills
    artists = [point_top_down, apsis_dot_top, influence_circle, influence_fill_top,
               point_side_view, apsis_dot_side, influence_sphere_side, influence_fill_side,
               day_text_top_down, angle_text_side, orbit_line_top_down, 
               orbit_line_side_view, orbit_center_side, seasonal_line_top]

    if state["paused"] and not force_render:
        return artists

    if not force_render:
        state["current_frame"] += state["speed"]
    
    current_f = int(state["current_frame"])
    total_days_elapsed = current_f / minutes_in_day 
    current_day_int = int((start_day + total_days_elapsed) % total_days_in_year)
    current_time = current_f % minutes_in_day
    current_year = start_year + int((start_day + total_days_elapsed) // total_days_in_year)
    
    rotational_angle = 2 * np.pi * (total_days_elapsed / (total_days_in_year * years_per_rotation)) if state["rotation_enabled"] else 0
    
    a, b = treaty_radius, treaty_radius * np.sqrt(1 - treaty_eccentricity)
    
    def transform_point(orb_angle):
        x_l, y_l = a * np.cos(orb_angle), b * np.sin(orb_angle)
        # Apply the fixed 7.25 inclination relative to the orbital plane
        x_t, y_t, z_t = x_l * np.cos(fixed_inclination), y_l, x_l * np.sin(fixed_inclination)
        # Then rotate by the precession (orbital rotation)
        x_rot = x_t * np.cos(rotational_angle) - y_t * np.sin(rotational_angle)
        y_rot = x_t * np.sin(rotational_angle) + y_t * np.cos(rotational_angle)
        return x_rot, y_rot, z_t + treaty_height

    treaty_orbit_angle = 2 * np.pi * current_time / minutes_in_day
    x_rot, y_rot, z_final = transform_point(treaty_orbit_angle)
    ax_rot, ay_rot, az_final = transform_point(0)

    # Viewing Direction logic
    if state["view_direction"] == "South": side_x, apsis_side_x = x_rot, ax_rot
    elif state["view_direction"] == "North": side_x, apsis_side_x = -x_rot, -ax_rot
    elif state["view_direction"] == "West": side_x, apsis_side_x = -y_rot, -ay_rot
    else: side_x, apsis_side_x = y_rot, ay_rot

    # Update Area of Influence
    height_diff = abs(z_final)
    influence_radius = np.sqrt(max(0, R**2 - height_diff**2)) if height_diff <= R else 0
    if influence_radius > 0:
        inf_x, inf_y = x_rot + influence_radius * np.cos(theta), y_rot + influence_radius * np.sin(theta)
        influence_circle.set_data(inf_x, inf_y)
        influence_fill_top.set_xy(np.column_stack([inf_x, inf_y]))
    else:
        influence_circle.set_data([], [])
        influence_fill_top.set_xy(np.empty((0, 2)))
    
    point_top_down.set_data([x_rot], [y_rot])
    apsis_dot_top.set_data([ax_rot], [ay_rot])
    
    # Orbit Lines
    t_x_l, t_y_l = a * np.cos(theta), b * np.sin(theta)
    t_x_t, t_y_t, t_z_t = t_x_l * np.cos(fixed_inclination), t_y_l, t_x_l * np.sin(fixed_inclination)
    orb_x = t_x_t * np.cos(rotational_angle) - t_y_t * np.sin(rotational_angle)
    orb_y = t_x_t * np.sin(rotational_angle) + t_y_t * np.cos(rotational_angle)
    orbit_line_top_down.set_data(orb_x, orb_y)

    # Side view
    inf_side_x, inf_side_z = side_x + R * np.cos(theta), z_final + R * np.sin(theta)
    influence_sphere_side.set_data(inf_side_x, inf_side_z)
    influence_fill_side.set_xy(np.column_stack([inf_side_x, inf_side_z]))
    point_side_view.set_data([side_x], [z_final])
    apsis_dot_side.set_data([apsis_side_x], [az_final])
    
    if state["view_direction"] == "South": orbit_side_proj = orb_x
    elif state["view_direction"] == "North": orbit_side_proj = -orb_x
    elif state["view_direction"] == "West": orbit_side_proj = -orb_y
    else: orbit_side_proj = orb_y
    orbit_line_side_view.set_data(orbit_side_proj, treaty_height + t_z_t)
    
    # Seasons (Divide logic)
    node_angle = rotational_angle + np.pi/2
    for f in fills: f.remove()
    fills = []
    if state["seasonal_semicircle"]:
        seasonal_line_top.set_data([-plane_radius * 1.2 * np.cos(node_angle), plane_radius * 1.2 * np.cos(node_angle)], 
                                  [-plane_radius * 1.2 * np.sin(node_angle), plane_radius * 1.2 * np.sin(node_angle)])
        f_theta = np.linspace(node_angle, node_angle + np.pi, 100)
        # Swapped colors: Blue for the side the orbit tilts away from, Red for where it tilts toward.
        fills.extend(ax1.fill(np.append(plane_radius * 1.3 * np.cos(f_theta), 0), np.append(plane_radius * 1.3 * np.sin(f_theta), 0), color='blue', alpha=0.1, zorder=0))
        fills.extend(ax1.fill(np.append(plane_radius * 1.3 * np.cos(f_theta + np.pi), 0), np.append(plane_radius * 1.3 * np.sin(f_theta + np.pi), 0), color='red', alpha=0.1, zorder=0))
    else:
        seasonal_line_top.set_data([], [])

    orbit_center_side.set_data([0], [treaty_height])
    
    h, m = divmod(current_time, 60)
    day_text_top_down.set_text(f'Year: {current_year}\nDay: {current_day_int + 1}\nTime: {int(h):02d}:{int(m):02d}\nStatus: {"PAUSED" if state["paused"] else "RUNNING"}')
    angle_text_side.set_text(f'Viewing: {state["view_direction"]}\nFixed Inclination: {np.degrees(fixed_inclination):.2f}°\nRotation: {np.degrees(rotational_angle)%360:.2f}°')
    
    return artists + fills

ani = FuncAnimation(fig, update, interval=20, blit=True, cache_frame_data=False)
plt.show()