### A PORTION OF, OR ALL OF, THE CODE CONTAINED WITHIN THIS FILE WAS GENERATED BY AN LLM.
#!/usr/bin/env python3
"""
git_md_summary.py

Interactive tool that, given one or more commit SHA‑1s, prints a Markdown
table summarising which Markdown pages were changed and **how** they were
changed.

Features
--------
* Absolute wiki‑links that start **after** the repository’s `content/`
  folder:   [[Encyclopedia Mysenvaria/History/God‑War Era/God Councils|God Councils]]
* Only pages whose front‑matter contain `type: article` are shown,
  **except** for newly‑added or removed pages where the front‑matter may
  be missing – those are still listed.
* The link label is taken from the `title:` front‑matter field **without
  surrounding quotes**.
* “Links Only” detects markdown links, wiki‑style links and image links.
* “Metadata Only” / “Status Updates” fire when the **only** change touches
  front‑matter.
* Minor vs. Major edits are decided by paragraph‑count **ignoring yaml**,
  with a special rule that heading‑only restructures are always Minor.
* New‑page, removed‑page and rename handling are now reliable.
* Table rows are ordered (lowest row wins) exactly as you asked.
"""

import argparse
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Set, Tuple

# ----------------------------------------------------------------------
# Table order – the *lowest* row (largest index) wins.
CATEGORIES = [
    "Metadata Only",
    "Links Only",
    "Minor Edits",
    "Major Edits",
    "Status Updates",
    "New Pages",
    "Removed Pages",
]

# ----------------------------------------------------------------------
# Heuristics – tweak them via CLI arguments.
MAX_PARAGRAPH_BLOCKS_FOR_MINOR = 1           # 1 block → Minor, >1 → Major
HEADING_REGEX = re.compile(r"^[+-]\s*#+\s")   # +## Heading
FRONTMATTER_REGEX = re.compile(r"^[+-]\s*[\w-]+:\s*")
STATUS_REGEX = re.compile(r"^[+-]\s*status\s*:", re.I)
MARKDOWN_LINK_REGEX = re.compile(r"\[[^\]]*\]\([^\)]+\)")
WIKILINK_REGEX = re.compile(r"\[\[[^\]]+\]\]")
IMAGE_LINK_REGEX = re.compile(
    r"!\[[^\]]*\]\([^\)]+\)|!\[\[[^\]]+\]\]"
)

# ----------------------------------------------------------------------
def run_git(args: List[str]) -> str:
    """Run a git command and return its stdout (decoded)."""
    result = subprocess.run(
        ["git"] + args,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=True,
    )
    return result.stdout.strip()


# ----------------------------------------------------------------------
def ask_for_shas() -> List[str]:
    """Prompt the user for one or more commit SHA‑1s."""
    print(
        "\nEnter one or more commit SHA‑1s (space‑ or comma‑separated)."
        "\nPress <Enter> on a blank line when you are done.\n"
    )
    lines = []
    while True:
        try:
            line = input("> ").strip()
        except EOFError:      # VS Code may feed EOF when run non‑interactively
            break
        if line == "":
            break
        lines.append(line)

    if not lines:
        sys.stderr.write("❌ No SHA supplied – aborting.\n")
        sys.exit(1)

    raw = " ".join(lines)
    return [tok for tok in re.split(r"[,\s]+", raw) if tok]


# ----------------------------------------------------------------------
def markdown_changes(sha: str) -> List[Dict[str, Path]]:
    """
    Return a list of dicts describing every *.md* file that changed in *sha*.
    Each dict contains:

    * `path`   – the *current* path (i.e. the destination of a rename)
    * `status` – one of "A", "M", "D", or "R"
    * `src`    – for a rename the original path, otherwise same as `path`
    """
    raw = run_git(
        ["diff", "--name-status", "-M", f"{sha}^!", "--", "*.md"]
    )
    entries: List[Dict[str, Path]] = []
    for line in raw.splitlines():
        parts = line.split("\t")
        flag = parts[0]
        if flag.startswith("R"):                 # rename: "R100\told\tnew"
            src_path = Path(parts[1])
            dst_path = Path(parts[2])
            # record removal of the old name
            entries.append(
                {"path": src_path, "status": "D", "src": src_path}
            )
            # record addition of the new name
            entries.append(
                {"path": dst_path, "status": "A", "src": src_path}
            )
        else:
            path = Path(parts[1])
            entries.append(
                {"path": path, "status": flag, "src": path}
            )
    return entries


# ----------------------------------------------------------------------
def diff_of_file(sha: str, path: Path) -> str:
    """
    Return the zero‑context diff for *path* in commit *sha*.
    """
    return run_git(
        ["diff", "-U0", f"{sha}^!", "--", str(path)]
    )


# ----------------------------------------------------------------------
def parse_front_matter(file_path: Path) -> Tuple[Dict[str, str], bool]:
    """
    Parse YAML front‑matter from a real file on disk.
    Returns a dict and a flag indicating whether a block was found.
    """
    if not file_path.is_file():
        return {}, False

    with file_path.open(encoding="utf-8") as f:
        lines = f.readlines()

    if not lines or not lines[0].strip().startswith("---"):
        return {}, False

    fm_lines = []
    for line in lines[1:]:
        if line.strip().startswith("---"):
            break
        fm_lines.append(line.rstrip("\n"))

    fm: Dict[str, str] = {}
    for line in fm_lines:
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        # Strip surrounding single‑ or double‑quotes
        if (value.startswith("'") and value.endswith("'")) or (
            value.startswith('"') and value.endswith('"')
        ):
            value = value[1:-1]
        fm[key.strip().lower()] = value.strip()
    return fm, True


def parse_front_matter_at_commit(path: Path, sha: str) -> Tuple[Dict[str, str], bool]:
    """
    Extract front‑matter for *path* as it existed in *sha*.
    Used for files that have been deleted in the commit we are analysing.
    """
    # Fast path – try the working tree first
    fm, ok = parse_front_matter(path)
    if ok:
        return fm, ok

    # Fallback – read the blob directly from the commit
    try:
        content = run_git(["show", f"{sha}:{str(path)}"])
    except subprocess.CalledProcessError:
        return {}, False

    lines = content.splitlines()
    if not lines or not lines[0].strip().startswith("---"):
        return {}, False

    fm_lines = []
    for line in lines[1:]:
        if line.strip().startswith("---"):
            break
        fm_lines.append(line.rstrip("\n"))

    fm = {}
    for line in fm_lines:
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        if (value.startswith("'") and value.endswith("'")) or (
            value.startswith('"') and value.endswith('"')
        ):
            value = value[1:-1]
        fm[key.strip().lower()] = value.strip()
    return fm, True


# ----------------------------------------------------------------------
def wikilink(path: Path, title: str) -> str:
    """
    Build an absolute wiki‑link that starts *after* the `content/` folder.
    Example:
        repo/content/Encyclopedia Mysenvaria/History/God‑War Era/God Councils.md
    becomes:
        [[Encyclopedia Mysenvaria/History/God‑War Era/God Councils|God Councils]]
    """
    try:
        rel_path = path.relative_to("content")
    except ValueError:
        rel_path = path
    wiki_path = str(rel_path.with_suffix("")).replace("\\", "/")
    return f"[[{wiki_path}\|{title}]]"


# ----------------------------------------------------------------------
def split_yaml_and_body(diff: str) -> Tuple[List[str], List[str]]:
    """
    Split a diff into front‑matter lines (`yaml_lines`) and the rest of the
    body (`body_lines`).  Both keep the leading +/- so the rest of the code
    can reuse them unchanged.
    """
    yaml_lines: List[str] = []
    body_lines: List[str] = []

    for raw in diff.splitlines():
        if not (raw.startswith("+") or raw.startswith("-")):
            continue                     # ignore diff metadata
        if raw.startswith(("+++", "---")):
            continue                     # ignore file‑header lines

        if FRONTMATTER_REGEX.match(raw):
            yaml_lines.append(raw)
        else:
            body_lines.append(raw)

    return yaml_lines, body_lines


# ----------------------------------------------------------------------
def count_paragraph_blocks(lines: List[str]) -> int:
    """
    Count contiguous changed‑line blocks separated by a blank line.
    Used for the Minor / Major decision when we fall back to paragraph
    counting.
    """
    block_cnt = 0
    inside = False
    for raw in lines:
        stripped = raw[1:].strip()          # drop the leading +/- first
        if stripped == "":
            if inside:
                block_cnt += 1
                inside = False
        else:
            inside = True
    if inside:
        block_cnt += 1
    return block_cnt


def is_heading_line(line: str) -> bool:
    """True if the added/removed line is a Markdown heading."""
    return bool(HEADING_REGEX.match(line))


def count_words(lines: List[str]) -> int:
    """Return the total number of words in a list of +/- lines."""
    total = 0
    for raw in lines:
        total += len(raw[1:].split())
    return total


# ----------------------------------------------------------------------
def categorize(
    diff: str,
    status_flag: str,
    mode: str = "hybrid",
    minor_word_thr: int = 30,
    major_word_thr: int = 150,
) -> Set[str]:
    """
    Return every category that *could* apply to a file.  The final
    category (the lowest row) will be selected later.
    """
    cats: Set[str] = set()

    # --------------------------------------------------------------
    # New / removed pages win immediately.
    if status_flag == "A":
        cats.add("New Pages")
        return cats
    if status_flag == "D":
        cats.add("Removed Pages")
        return cats

    # --------------------------------------------------------------
    yaml_lines, body_lines = split_yaml_and_body(diff)

    # --------------------------------------------------------------
    # Front‑matter‑only → Metadata Only / Status Updates
    if yaml_lines and not body_lines:
        if any(STATUS_REGEX.match(l) for l in yaml_lines):
            cats.add("Status Updates")
        else:
            cats.add("Metadata Only")
        return cats

    # --------------------------------------------------------------
    # No body change → nothing else to classify.
    if not body_lines:
        return cats

    # 1️⃣ Links‑Only (on body only)
    if all(
        MARKDOWN_LINK_REGEX.search(l)
        or WIKILINK_REGEX.search(l)
        or IMAGE_LINK_REGEX.search(l)
        for l in body_lines
    ):
        cats.add("Links Only")

    # 2️⃣ Heading‑only → always Minor
    if all(is_heading_line(l) for l in body_lines):
        cats.add("Minor Edits")
        return cats

    # 3️⃣ Word‑count based decision (used by hybrid & words‑only)
    added_words = count_words([l for l in body_lines if l.startswith("+")])
    removed_words = count_words([l for l in body_lines if l.startswith("-")])
    word_delta = abs(added_words - removed_words)

    if mode in ("words-only", "hybrid"):
        if word_delta <= minor_word_thr:
            cats.add("Minor Edits")
            if mode == "words-only":
                return cats
        elif word_delta > major_word_thr:
            cats.add("Major Edits")
            if mode == "words-only":
                return cats
        # hybrid falls through to paragraph‑count for the middle range

    # 4️⃣ Paragraph‑block fallback (used by hybrid & paragraphs)
    block_cnt = count_paragraph_blocks(body_lines)
    if block_cnt <= MAX_PARAGRAPH_BLOCKS_FOR_MINOR:
        cats.add("Minor Edits")
    else:
        cats.add("Major Edits")

    return cats


# ----------------------------------------------------------------------
def main() -> None:
    # -------------------- CLI options --------------------
    parser = argparse.ArgumentParser(
        description="Generate a wiki‑link changelog for a set of commits."
    )
    parser.add_argument(
        "--mode",
        choices=["hybrid", "words-only", "paragraphs"],
        default="hybrid",
        help=(
            "How to decide Minor vs Major edits:\n"
            "· hybrid (default) – word count with paragraph fallback.\n"
            "· words-only – pure word‑count thresholds.\n"
            "· paragraphs – legacy paragraph‑block counting."
        ),
    )
    parser.add_argument(
        "--minor-threshold",
        type=int,
        default=30,
        help="Word‑count delta ≤ this is Minor (default: %(default)s).",
    )
    parser.add_argument(
        "--major-threshold",
        type=int,
        default=150,
        help="Word‑count delta > this is Major (default: %(default)s).",
    )
    args, _ = parser.parse_known_args()

    # -------------------- Get SHA list --------------------
    shas = ask_for_shas()

    # Mapping: file → (set of categories, title)
    file_info: Dict[Path, Tuple[Set[str], str]] = defaultdict(
        lambda: (set(), "")
    )

    for sha in shas:
        entries = markdown_changes(sha)

        for entry in entries:
            md_path: Path = entry["path"]
            status_flag: str = entry["status"]

            # ------------------------------------------------------
            # Get front‑matter *as it existed*.
            if status_flag == "D":
                # file was removed → look at the parent commit
                fm, _ = parse_front_matter_at_commit(md_path, f"{sha}^")
            else:
                fm, _ = parse_front_matter_at_commit(md_path, sha)

            # ------------------------------------------------------
            # Keep only pages that are articles – **except** for new or removed
            # pages where we may not have a front‑matter block yet.
            if fm.get("type", "").lower() != "article":
                if status_flag not in ("A", "D"):
                    continue   # skip non‑article normal edits

            # Title for the link – fall back to cleaned filename stem
            title = fm.get(
                "title",
                md_path.stem.replace("_", " ").replace("-", " "),
            )

            # ------------------------------------------------------
            # Diff for categorisation.
            diff_txt = diff_of_file(sha, md_path)

            # Determine categories (pass CLI options through).
            cats = categorize(
                diff_txt,
                status_flag,
                mode=args.mode,
                minor_word_thr=args.minor_threshold,
                major_word_thr=args.major_threshold,
            )

            # Accumulate – a file may appear in several commits.
            prev_cats, _ = file_info[md_path]
            prev_cats.update(cats)
            file_info[md_path] = (prev_cats, title)

    # ------------------------------------------------------------------
    # Choose the *lowest* row (largest index) for each file.
    rows: Dict[str, List[str]] = {cat: [] for cat in CATEGORIES}
    for md_path, (cats, title) in file_info.items():
        if not cats:
            continue
        best = max(cats, key=lambda c: CATEGORIES.index(c))
        rows[best].append(wikilink(md_path, title))

    # ------------------------------------------------------------------
    # Print the markdown table (comma‑separated wiki‑links).
    print("\n| **Type of Edit**   | **Impacted Articles** |")
    print("| ------------------ | --------------------- |")
    for cat in CATEGORIES:
        links = ", ".join(sorted(rows[cat])) if rows[cat] else ""
        print(f"| **{cat}** | {links} |")


if __name__ == "__main__":
    main()
