### A PORTION OF, OR ALL OF, THE CODE CONTAINED WITHIN THIS FILE WAS GENERATED BY AN LLM.
"""
git_md_summary.py

An interactive tool for an encyclopedia repo that lives under a top‑level
`content/` folder.

Features
--------
* Absolute wiki‑links that start **after** `content/`:
      [[Encyclopedia Mysenvaria/History/God‑War Era/God Councils|God Councils]]
* Only pages whose front‑matter contain   `type: article`   are shown.
* The link label is taken from the `title:` front‑matter field **without
  surrounding quotes**.
* “Links Only” now detects:
      – markdown links            `[text](url)`
      – wiki‑style links          `[[Page]]` or `[[Page|Label]]`
      – image links (markdown or wiki) `![](url)` and `![[image.png]]`
* **Metadata‑only** rule:
      – If *all* changes in a commit are inside the front‑matter, the file
        is placed in **Metadata Only** (or **Status Updates** if the yaml
        contains a `status:` line).  Any body change makes the yaml part
        irrelevant for the other categories.
* Minor / Major edits are decided by **paragraph count** **ignoring yaml**
  lines:
      – 1 paragraph‑change block → Minor Edits  
      – >1 paragraph‑change block → Major Edits
* Table rows are ordered (lowest row wins) exactly as you asked.

Run inside VS Code with *Right‑click → Run Python File in Terminal*,
paste one or more commit SHA‑1s, and the table prints to the terminal.
"""

import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Set, Tuple

# ----------------------------------------------------------------------
# The order matters – the *lowest* row (largest index) wins.
CATEGORIES = [
    "Metadata Only",
    "Links Only",
    "Minor Edits",
    "Major Edits",
    "Status Updates",
    "New Pages",
    "Removed Pages",
]

# ----------------------------------------------------------------------
# Heuristics – tweak them if you like.
MAX_PARAGRAPH_BLOCKS_FOR_MINOR = 1           # 1 block → Minor, >1 → Major

# Regexes used for classification
FRONTMATTER_REGEX = re.compile(r"^[+-]\s*[\w-]+:\s*")   # +title: …
STATUS_REGEX = re.compile(r"^[+-]\s*status\s*:", re.I)   # +status: …
MARKDOWN_LINK_REGEX = re.compile(r"\[[^\]]*\]\([^\)]+\)")          # [text](url)
WIKILINK_REGEX = re.compile(r"\[\[[^\]]+\]\]")                  # [[Page]]
IMAGE_LINK_REGEX = re.compile(
    r"!\[[^\]]*\]\([^\)]+\]|!\[\[[^\]]+\]\]"
)  # ![alt](url) or ![[img.png]]


# ----------------------------------------------------------------------
def run_git(args: List[str]) -> str:
    """Run a git command and return its stdout (decoded)."""
    result = subprocess.run(
        ["git"] + args,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=True,
    )
    return result.stdout.strip()


# ----------------------------------------------------------------------
def ask_for_shas() -> List[str]:
    """Prompt the user for one or more commit SHA‑1s."""
    print(
        "\nEnter one or more commit SHA‑1s (space‑ or comma‑separated)."
        "\nPress <Enter> on a blank line when you are done.\n"
    )
    lines = []
    while True:
        try:
            line = input("> ").strip()
        except EOFError:      # VS Code may feed EOF when run non‑interactively
            break
        if line == "":
            break
        lines.append(line)

    if not lines:
        sys.stderr.write("❌ No SHA supplied – aborting.\n")
        sys.exit(1)

    raw = " ".join(lines)
    return [tok for tok in re.split(r"[,\s]+", raw) if tok]


# ----------------------------------------------------------------------
def markdown_files_changed(sha: str) -> Set[Path]:
    """
    Return the set of *.md* files that changed in *sha* (adds, deletes,
    modifications). Works for normal and merge commits.
    """
    diff_output = run_git(
        ["diff", "--name-only", f"{sha}^!", "--", "*.md"]
    )
    return {Path(p) for p in diff_output.splitlines() if p}


def diff_of_file(sha: str, path: Path) -> str:
    """Return the zero‑context diff for *path* in *sha*."""
    return run_git(
        ["diff", "-U0", f"{sha}^!", "--", str(path)]
    )


# ----------------------------------------------------------------------
def parse_front_matter(file_path: Path) -> Tuple[Dict[str, str], bool]:
    """
    Return a dict of YAML front‑matter from *file_path* (as it exists on
    disk right now) and a flag indicating whether a front‑matter block
    was found.
    """
    if not file_path.is_file():
        return {}, False

    with file_path.open(encoding="utf-8") as f:
        lines = f.readlines()

    if not lines or not lines[0].strip().startswith("---"):
        return {}, False

    fm_lines = []
    for line in lines[1:]:
        if line.strip().startswith("---"):
            break
        fm_lines.append(line.rstrip("\n"))

    fm: Dict[str, str] = {}
    for line in fm_lines:
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        # Strip surrounding quotes if they exist – solves the “title with quotes”
        value = value.strip()
        if (value.startswith("'") and value.endswith("'")) or (
            value.startswith('"') and value.endswith('"')
        ):
            value = value[1:-1]
        fm[key.strip().lower()] = value.strip()
    return fm, True


# ----------------------------------------------------------------------
def wikilink(path: Path, title: str) -> str:
    """
    Build an **absolute** wiki‑link that starts *after* the repository
    `content/` directory.

    Example (repo layout):
        repo/
            content/
                Encyclopedia Mysenvaria/
                    History/
                        God‑War Era/
                            God Councils.md

    Returns:
        [[Encyclopedia Mysenvaria/History/God‑War Era/God Councils|God Councils]]
    """
    try:
        rel_path = path.relative_to("content")
    except ValueError:
        rel_path = path

    wiki_path = str(rel_path.with_suffix("")).replace("\\", "/")
    return f"[[{wiki_path}\|{title}]]"


# ----------------------------------------------------------------------
def split_yaml_and_body(diff: str) -> Tuple[List[str], List[str]]:
    """
    Split a diff into two lists:

    * `yaml_lines` – lines that belong to the front‑matter (match
      FRONTMATTER_REGEX)
    * `body_lines` – every other added/removed line.

    Both lists preserve the leading `+` / `-` characters because the
    classification functions expect them.
    """
    yaml_lines: List[str] = []
    body_lines: List[str] = []

    for raw in diff.splitlines():
        if not (raw.startswith("+") or raw.startswith("-")):
            continue                     # ignore diff headers
        # Skip the context header lines "+++" / "---"
        if raw.startswith(("+++", "---")):
            continue

        # Decide if it is yaml/front‑matter
        if FRONTMATTER_REGEX.match(raw):
            yaml_lines.append(raw)
        else:
            body_lines.append(raw)

    return yaml_lines, body_lines


# ----------------------------------------------------------------------
def count_paragraph_blocks(lines: List[str]) -> int:
    """
    Count *paragraph‑change blocks* in a list of added/removed lines.
    Blank lines (or lines containing only whitespace) separate blocks.
    """
    block_cnt = 0
    inside = False

    for raw in lines:
        stripped = raw[1:].strip()          # drop the leading +/-
        if stripped == "":
            if inside:
                block_cnt += 1
                inside = False
        else:
            inside = True

    if inside:
        block_cnt += 1
    return block_cnt


# ----------------------------------------------------------------------
def categorize(diff: str, status_flag: str) -> Set[str]:
    """
    Return every category that *could* apply to a file.  The final
    category (the lowest row) will be selected later.
    """
    cats: Set[str] = set()

    # --------------------------------------------------------------
    # New / removed pages win immediately.
    if status_flag == "A":
        cats.add("New Pages")
        return cats
    if status_flag == "D":
        cats.add("Removed Pages")
        return cats

    # --------------------------------------------------------------
    # Split the diff into yaml and body parts.
    yaml_lines, body_lines = split_yaml_and_body(diff)

    # --------------------------------------------------------------
    # If *only* yaml changed → Metadata‑Only (or Status Updates).
    if yaml_lines and not body_lines:
        if any(STATUS_REGEX.match(l) for l in yaml_lines):
            cats.add("Status Updates")
        else:
            cats.add("Metadata Only")
        return cats

    # --------------------------------------------------------------
    # At this point there is at least one body line, so we ignore yaml
    # for the remaining categories.

    # 1️⃣ Links‑only detection (on body lines only)
    if all(
        MARKDOWN_LINK_REGEX.search(l)
        or WIKILINK_REGEX.search(l)
        or IMAGE_LINK_REGEX.search(l)
        for l in body_lines
    ):
        cats.add("Links Only")

    # 2️⃣ Paragraph‑block count → Minor vs Major (body only)
    block_cnt = count_paragraph_blocks(body_lines)
    if block_cnt <= MAX_PARAGRAPH_BLOCKS_FOR_MINOR:
        cats.add("Minor Edits")
    else:
        cats.add("Major Edits")

    # 3️⃣ Status Updates – only make sense when the *only* change was a
    #    yaml status line (handled above).  If there is a body change we
    #    do **not** add Status Updates because the edit is no longer a
    #    pure status change.
    return cats


# ----------------------------------------------------------------------
def main() -> None:
    shas = ask_for_shas()

    # Mapping: file → (set of categories, title)
    file_info: Dict[Path, Tuple[Set[str], str]] = defaultdict(
        lambda: (set(), "")
    )

    for sha in shas:
        changed_files = markdown_files_changed(sha)

        for md_path in changed_files:
            # Determine git status (A, M, D, etc.)
            status_line = run_git(
                ["diff", "--name-status", f"{sha}^!", "--", str(md_path)]
            ).strip()
            status_flag = status_line.split("\t")[0] if status_line else "M"

            # Parse front‑matter for title & type
            fm, _ = parse_front_matter(md_path)

            # Keep only pages marked as `type: article`
            if fm.get("type", "").lower() != "article":
                continue

            # Title for the link – fall back to the filename stem
            title = fm.get(
                "title",
                md_path.stem.replace("_", " ").replace("-", " ")
            )

            # Diff for categorisation
            diff_txt = diff_of_file(sha, md_path)

            # Determine categories
            cats = categorize(diff_txt, status_flag)

            # Accumulate (a file can be touched in several commits)
            prev_cats, _ = file_info[md_path]
            prev_cats.update(cats)
            file_info[md_path] = (prev_cats, title)

    # ------------------------------------------------------------------
    # Choose the lowest row (largest index) for each file.
    rows: Dict[str, List[str]] = {cat: [] for cat in CATEGORIES}
    for md_path, (cats, title) in file_info.items():
        if not cats:
            continue
        best = max(cats, key=lambda c: CATEGORIES.index(c))
        rows[best].append(wikilink(md_path, title))

    # ------------------------------------------------------------------
    # Print the markdown table (comma‑separated wiki‑links)
    print("\n| **Type of Edit**   | **Impacted Articles** |")
    print("| ------------------ | --------------------- |")
    for cat in CATEGORIES:
        links = ", ".join(sorted(rows[cat])) if rows[cat] else ""
        print(f"| **{cat}** | {links} |")


if __name__ == "__main__":
    main()
