### A PORTION OF, OR ALL OF, THE CODE CONTAINED WITHIN THIS FILE WAS GENERATED BY AN LLM.
#!/ user/bin/env python3
"""
git_md_summary.py - Optimized for Encyclopedia Ledgers
"""

import argparse
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Set, Tuple, Optional

# ===================== CONFIG & CATEGORIES =====================
# Set this to True to see detailed lifecycle flags for every file in the terminal
DEBUG_MODE = True 

CATEGORIES = [
    "Edited Articles",
    "New Articles",
    "Removed Articles",
]

EXCLUDE_COMMIT_PATTERNS = ["github-actions", "chore(ci)"]
EXCLUDE_DIRS = {".obsidian", "Meta", "Templates"}

# ===================== GIT UTILITIES =====================

def run_git(args: List[str]) -> str:
    try:
        # Added --no-pager to prevent Git from hanging on a pager prompt
        # Added encoding='utf-8' and errors='replace' for Windows compatibility
        process = subprocess.Popen(
            ["git", "--no-pager"] + args,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding='utf-8',
            errors='replace'
        )
        
        stdout, stderr = process.communicate()
        
        if process.returncode != 0:
            return ""
            
        return stdout.strip() if stdout else ""
    except Exception:
        return ""

def get_commits_from_input(input_str: str) -> List[str]:
    """
    Parses input and returns a chronologically sorted list of unique, valid SHAs.
    """
    tokens = [t.strip() for t in re.split(r'[,\s]+', input_str) if t.strip()]
    if not tokens:
        return []

    print(f"[*] Resolving {len(tokens)} commit tokens...")
    
    # Logic Fix: If user provides a range (contains '..'), we use standard log.
    # If they provide individual SHAs, we use --no-walk to prevent walking back to the beginning of time.
    is_range = any(".." in t for t in tokens)
    
    if is_range:
        cmd = ["log", "--reverse", "--format=%H"] + tokens
    else:
        # --no-walk ensures only the specific SHAs provided are returned
        cmd = ["log", "--reverse", "--no-walk", "--format=%H"] + tokens
        
    raw_output = run_git(cmd)
    
    if not raw_output:
        return []

    all_shas = [line.strip() for line in raw_output.splitlines() if line.strip()]
    
    seen = set()
    unique_shas = []
    for sha in all_shas:
        if sha not in seen:
            unique_shas.append(sha)
            seen.add(sha)

    valid_shas = []
    for sha in unique_shas:
        commit_info = run_git(["log", "-1", "--format=%an %s", sha]).lower()
        if any(pat in commit_info for pat in EXCLUDE_COMMIT_PATTERNS):
            continue
        valid_shas.append(sha)
        
    print(f"[+] Found {len(valid_shas)} valid commits to process.")
    return valid_shas

def get_file_metadata_at_sha(path_str: str, sha: str) -> Dict[str, str]:
    """Retrieves frontmatter metadata for a file at a specific commit."""
    try:
        content = run_git(["show", f"{sha}:{path_str}"])
        if not content: return {}
        
        metadata = {}
        # Simple regex for YAML frontmatter
        parts = re.split(r'^---\s*$', content, maxsplit=2, flags=re.MULTILINE)
        if len(parts) >= 3:
            fm_text = parts[1]
            for line in fm_text.splitlines():
                if ":" in line:
                    k, v = line.split(":", 1)
                    metadata[k.strip().lower()] = v.strip().strip('"').strip("'")
        
        return metadata
    except:
        return {}

def get_file_metadata_from_filesystem(path_str: str) -> Tuple[Optional[str], Optional[str]]:
    """Reads metadata from the local filesystem (HEAD state)."""
    try:
        path = Path(path_str)
        if not path.exists():
            return None, None
            
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read(2048) # Only read the beginning for speed
            type_match = re.search(r'^type:\s*(.*)$', content, re.MULTILINE | re.I)
            doc_type = type_match.group(1).strip().strip('"').strip("'").lower() if type_match else "article"
            title_match = re.search(r'^title:\s*(.*)$', content, re.MULTILINE | re.I)
            title = title_match.group(1).strip().strip('"').strip("'") if title_match else path.stem.replace("_", " ").replace("-", " ").title()
            return title, doc_type
    except:
        return None, None

# ===================== MAIN EXECUTION =====================

def main():
    parser = argparse.ArgumentParser(description="Encyclopedia Ledger Helper")
    parser.add_argument("input", nargs="*", help="SHAs or range")
    parser.add_argument("--all", action="store_true", help="Include all file types, not just articles")
    parser.add_argument("--debug", action="store_true", help="Override DEBUG_MODE and force debug output")
    args = parser.parse_args()

    active_debug = DEBUG_MODE or args.debug
    raw_input = " ".join(args.input)
    if not raw_input:
        raw_input = input("Enter SHAs or range: ").strip()
    
    shas = get_commits_from_input(raw_input)
    if not shas:
        print("No valid commits found.")
        return

    file_lifecycle = defaultdict(list)
    latest_metadata = {}

    print(f"[*] Analyzing diffs for {len(shas)} commits...")
    for idx, sha in enumerate(shas):
        short_sha = sha[:7]
        print(f"    [{idx+1}/{len(shas)}] Processing {short_sha}...")
        
        # Use diff-tree to find changed files in the commit
        # -r: recursive, -M: detect renames
        diff_summary = run_git(["diff-tree", "--no-commit-id", "--name-status", "-r", "-M", sha])
        if not diff_summary: continue

        for line in diff_summary.splitlines():
            parts = line.split("\t")
            if len(parts) < 2: continue
            
            status_raw, path_str = parts[0], parts[-1]
            status_flag = status_raw[0]

            if not path_str.lower().endswith(".md"): continue
            # Check if file is in excluded directory
            if any(exc in path_str.split('/') for exc in EXCLUDE_DIRS): continue
            
            print(f"        {status_flag} {path_str}")
            file_lifecycle[path_str].append(status_flag)

            # Metadata extraction (Strictly scoped to files in the diff)
            if status_flag == "D":
                # For deleted files, lookup the metadata from the commit immediately prior
                meta = get_file_metadata_at_sha(path_str, f"{sha}^")
                title = meta.get("title") or Path(path_str).stem.replace("-", " ").title()
                doc_type = meta.get("type", "article").lower()
                latest_metadata[path_str] = (title, doc_type)
            else:
                # Try filesystem for efficiency if it's an addition or modification
                title, doc_type = get_file_metadata_from_filesystem(path_str)
                if title:
                    latest_metadata[path_str] = (title, doc_type)
                else:
                    # Fallback to git show for files that might have been renamed or modified but not currently on disk
                    meta = get_file_metadata_at_sha(path_str, sha)
                    title = meta.get("title") or Path(path_str).stem.replace("-", " ").title()
                    doc_type = meta.get("type", "article").lower()
                    latest_metadata[path_str] = (title, doc_type)

    table_data = {cat: [] for cat in CATEGORIES}

    print(f"[*] Processing lifecycle for {len(file_lifecycle)} impacted files...")
    if active_debug:
        print(f"\n--- DEBUG: SCANNING {len(file_lifecycle)} UNIQUE FILES ---")

    for path_str, statuses in file_lifecycle.items():
        # Get metadata retrieved during the diff loop
        meta_entry = latest_metadata.get(path_str)
        if not meta_entry:
            continue
            
        title, doc_type = meta_entry
        
        if not args.all and doc_type != "article":
            if active_debug: print(f"SKIP (Type): {path_str} | Type: {doc_type}")
            continue

        is_new_in_range = 'A' in statuses or 'R' in statuses 
        is_deleted_at_end = statuses[-1] == 'D'
        is_transient = is_new_in_range and is_deleted_at_end
        
        if is_transient:
            if active_debug: print(f"SKIP (Transient): {path_str} | Flags: {statuses}")
            continue
            
        final_cat = "Edited Articles"
        if is_new_in_range:
            final_cat = "New Articles"
        elif is_deleted_at_end:
            final_cat = "Removed Articles"

        if active_debug:
            print(f"FILE: {path_str:<50} | CAT: {final_cat:<18} | FLAGS: {' -> '.join(statuses)}")

        if final_cat == "Removed Articles":
            table_data[final_cat].append(title)
        else:
            # Clean up the Obsidian link path
            clean_path = path_str
            if "content/" in path_str:
                clean_path = path_str.split("content/", 1)[1]
            
            link_target = clean_path.rsplit(".md", 1)[0]
            wiki_link = f"[[{link_target}\\|{title}]]"
            table_data[final_cat].append(wiki_link)

    print("[*] Formatting results...")
    output = ["\n| **Type of Edit** | **Impacted Articles** |", "| ---------------- | --------------------- |"]
    for cat in CATEGORIES:
        links = ", ".join(sorted(table_data[cat]))
        output.append(f"| **{cat}** | {links or '_None_'} |")

    print("\n" + "\n".join(output) + "\n")
    print("--- END OF LEDGER ---")

if __name__ == "__main__":
    main()