### A PORTION OF, OR ALL OF, THE CODE CONTAINED WITHIN THIS FILE WAS GENERATED BY AN LLM.
import pathlib
import json
import os
from collections import defaultdict
from typing import Dict, List, Any, Tuple, Optional
import re

# --- Configuration Constants ---
START_YEAR = -180
END_YEAR = 1499
DECADES_DIR_REL = "Encyclopedia Mysenvaria/Indexes/History/Decades"
CENTURIES_DIR_REL = "Encyclopedia Mysenvaria/Indexes/History/Centuries"
METADATA_JSON_PATH = "Meta/Programs/debug/metadata_aggregator/extracted_metadata.json"
DRY_RUN = False

# ----------------- Helper Functions -----------------

def year_link(year: int) -> str:
    year_text = year_suffix(year)

    decade_start = (year // 10) * 10
    decade_name = decade_title(decade_start)

    return (
        f"[[Encyclopedia Mysenvaria/Indexes/History/Decades/"
        f"{decade_name}#{year_text}|{year_text}]]"
    )

def find_content_root() -> pathlib.Path:
    curr = pathlib.Path.cwd()
    for _ in range(5):
        if (curr / "content").is_dir():
            return curr / "content"
        curr = curr.parent
    return pathlib.Path("./content")

def ensure_extracted_json(root: pathlib.Path) -> Dict[str, Any]:
    json_path = root / METADATA_JSON_PATH
    if not json_path.exists():
        print(f"[ERROR] Metadata file not found at {json_path}. Run aggregator first.")
        return {}
    with open(json_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def year_suffix(year: int) -> str:
    return f"{abs(year)} BT" if year < 0 else f"{year} AT"

def decade_title(start_year: int) -> str:
    return f"{abs(start_year)}s BT" if start_year < 0 else f"{start_year}s AT"

def get_ordinal_century(year: int) -> Tuple[int, str]:
    """Returns (century_number, suffix) e.g., (-180) -> (2, 'BT')"""
    if year < 0:
        val = (abs(year + 1) // 100) + 1
        return val, "BT"
    else:
        val = (year // 100) + 1
        return val, "AT"

def century_title_from_ordinal(val: int, suffix: str) -> str:
    if 11 <= (val % 100) <= 13:
        ord_val = f"{val}th"
    else:
        ord_val = f"{val}" + {1: "st", 2: "nd", 3: "rd"}.get(val % 10, "th")
    return f"{ord_val} Century {suffix}"

def get_century_bounds(val: int, suffix: str) -> Tuple[int, int]:
    """Returns (start_year, end_year) for a given ordinal century."""
    if suffix == "BT":
        # 1st BT: -100 to -1, 2nd BT: -200 to -101
        start = -(val * 100)
        end = -((val - 1) * 100 + 1)
        return start, end
    else:
        # 1st AT: 0 to 99, 2nd AT: 100 to 199
        start = (val - 1) * 100
        end = (val * 100) - 1
        return start, end

def season_day_label(norm_date: Any) -> Optional[str]:
    """Uses the new formal_without_year field from the aggregator."""
    if isinstance(norm_date, dict):
        return norm_date.get("formal_without_year")
    return None

def parse_year_day(inf_str: str) -> Tuple[int, Optional[int]]:
    if not inf_str: return 0, None
    if inf_str.startswith("-"):
        parts = inf_str[1:].split("-")
        y = int(parts[0]) * -1
        d = int(parts[1]) if len(parts) > 1 else None
    else:
        parts = inf_str.split("-")
        y = int(parts[0])
        d = int(parts[1]) if len(parts) > 1 else None
    return y, d

def escape_table_pipes(text: str) -> str:
    if not text: return ""
    return re.sub(r'(\[\[[^\]|]+)\|([^\]|]+\]\])', r'\1\|\2', text)

# ----------------- Data Processing -----------------

def build_timeline_data(raw_data: Dict[str, Any]):
    events_by_decade = defaultdict(lambda: defaultdict(list))
    births_by_decade = defaultdict(lambda: defaultdict(list))
    deaths_by_decade = defaultdict(lambda: defaultdict(list))
    relationships_by_decade = defaultdict(lambda: defaultdict(list))
    stars_by_decade = defaultdict(list)

    for page in raw_data.get("pages", []):
        meta = page.get("metadata", {})
        page_link = meta.get("link", "").strip("[]")
        page_title = meta.get("title", "Unknown")
        link_path = page_link.split('|')[0].strip() if "|" in page_link else page_link

        if "event" in meta and isinstance(meta["event"], list):
            for e in meta["event"]:
                for prefix in ("start", "end"):
                    d_obj = e.get(f"{prefix}_date")
                    desc = e.get(f"{prefix}_desc")
                    if isinstance(d_obj, dict) and desc and str(desc).strip():
                        y, d = parse_year_day(d_obj.get("informal", ""))
                        events_by_decade[(y // 10) * 10][y].append({
                            "day": d, "label": season_day_label(d_obj), "desc": desc.strip()
                        })

        if "person" in meta and isinstance(meta["person"], list):
            for p in meta["person"]:
                p_name = p.get("name", page_title)
                p_link = f"[[{link_path}|{p_name}]]"
                is_major = p.get("major_event", False)

                if is_major:
                    for key, grouping, verb_pfx in [("birth_date", births_by_decade, "d."), ("death_date", deaths_by_decade, "b.")]:
                        d_obj = p.get(key)
                        if isinstance(d_obj, dict):
                            y, d = parse_year_day(d_obj.get("informal", ""))
                            other_key = "death_date" if key == "birth_date" else "birth_date"
                            other_val = p.get(other_key)
                            suffix = ""
                            if isinstance(other_val, dict):
                                oy, _ = parse_year_day(other_val.get("informal", "0"))
                                suffix = f" ({verb_pfx} {year_link(oy)})"
                            grouping[(y // 10) * 10][y].append({
                                "day": d, "alpha": p_name, "text": f"- {p_link}{suffix}"
                            })

                if is_major and "spouses" in p and isinstance(p["spouses"], list):
                    for sp in p["spouses"]:
                        if not sp.get("major_event"): continue
                        s_name = sp.get("name", "Unknown")
                        for d_key, verb, other_v_pfx, other_key in [
                            ("start_date", "marries", "div.", "end_date"), 
                            ("end_date", "divorces", "mar.", "start_date")
                        ]:
                            d_obj = sp.get(d_key)
                            if isinstance(d_obj, dict):
                                y, d = parse_year_day(d_obj.get("informal", ""))
                                other_val = sp.get(other_key)
                                suffix = ""
                                if isinstance(other_val, dict):
                                    oy, _ = parse_year_day(other_val.get("informal", "0"))
                                    suffix = f" ({other_v_pfx} {year_link(oy)})"
                                relationships_by_decade[(y // 10) * 10][y].append({
                                    "day": d, "text": f"- {p_link} {verb} {s_name}{suffix}"
                                })

        if "star" in meta and isinstance(meta["star"], list):
            for s in meta["star"]:
                s_name = s.get("name", page_title)
                clean_star_desc = escape_table_pipes(s.get("desc", "").strip())
                s_link = f"[[{link_path}\\|{s_name}]]"
                for sub_key, actor_key in [("publications", "publishers"), ("translations", "translators")]:
                    if sub_key in s and isinstance(s[sub_key], list):
                        for item in s[sub_key]:
                            d_obj = item.get("date")
                            if not isinstance(d_obj, dict):
                                continue

                            y, d = parse_year_day(d_obj.get("informal", ""))
                            d_start = (y // 10) * 10

                            if item.get("major_event") and item.get("desc", "").strip():
                                events_by_decade[d_start][y].append({
                                    "day": d,
                                    "label": season_day_label(d_obj),
                                    "desc": item["desc"].strip()
                                })
                # Add only the original publication to the star table
                if "publications" in s and isinstance(s["publications"], list):

                    publications = []

                    for pub in s["publications"]:
                        d_obj = pub.get("date")
                        if not isinstance(d_obj, dict):
                            continue

                        y, d = parse_year_day(d_obj.get("informal", ""))
                        publications.append((y, d, pub, d_obj))

                    if publications:
                        earliest_y, earliest_d, earliest_pub, earliest_d_obj = min(
                            publications,
                            key=lambda x: (
                                x[0],
                                x[1] if x[1] is not None else 999
                            )
                        )

                        actors_str = escape_table_pipes(
                            ", ".join(earliest_pub.get("publishers", []))
                        )

                        stars_by_decade[(earliest_y // 10) * 10].append({
                            "year": earliest_y,
                            "day": earliest_d,
                            "alpha": s_name,
                            "row": {
                                "name_link": s_link,
                                "date_year": earliest_y,
                                "date_obj": earliest_d_obj,
                                "actors": actors_str,
                                "desc": clean_star_desc
                            }
                        })

    return events_by_decade, births_by_decade, deaths_by_decade, relationships_by_decade, stars_by_decade

# ----------------- Renderers -----------------

def render_events(events_map: Dict[int, List[Dict[str, Any]]]) -> str:
    if not events_map: return ""
    output = ["# Events"]
    for year in sorted(events_map.keys()):
        output.append(f"## {year_suffix(year)}")
        date_groups = defaultdict(list)
        for item in events_map[year]:
            date_groups[(item['day'], item['label'])].append(item['desc'])
        for (day_val, label) in sorted(date_groups.keys(), key=lambda x: (x[0] is None, x[0] or 0)):
            descs = date_groups[(day_val, label)]
            if label:
                if len(descs) > 1:
                    output.append(f"- {label}")
                    output.extend(f"  - {d}" for d in descs)
                else:
                    output.append(f"- {label} — {descs[0]}")
            else:
                output.extend(f"- {d}" for d in descs)
    return "\n".join(output) + "\n"

def render_people(births, deaths, relationships) -> str:
    if not any((births, deaths, relationships)): return ""
    output = ["# Significant People"]
    for title, data in [("Births", births), ("Deaths", deaths), ("Relationships", relationships)]:
        if not data: continue
        output.append(f"## {title}")
        for year in sorted(data.keys()):
            output.append(f"### {year_suffix(year)}")
            sort_key = lambda x: (x['day'] is None, x['day'] or 0, x.get('alpha', ''))
            output.extend(item['text'] for item in sorted(data[year], key=sort_key))
    return "\n".join(output) + "\n"

def render_stars(stars_list: List[Dict[str, Any]]) -> str:
    if not stars_list: return ""
    output = ["# Stars", "| Name | Date | Publisher(s) | Description |", "| --- | --- | --- | --- |"]
    for s in sorted(stars_list, key=lambda x: (x['year'], x['day'] is None, x['day'] or 0)):
        r = s['row']
        d_lbl = season_day_label(r['date_obj'])
        date_str = f"{d_lbl}, {year_suffix(r['date_year'])}" if d_lbl else year_suffix(r['date_year'])
        output.append(f"| {r['name_link']} | {date_str} | {r['actors']} | {r['desc']} |")
    return "\n".join(output) + "\n"

def main():
    root = find_content_root()
    raw_data = ensure_extracted_json(root)
    if not raw_data: return

    ev_m, bi_m, de_m, re_m, st_m = build_timeline_data(raw_data)
    out_dir = root / DECADES_DIR_REL
    out_dir.mkdir(parents=True, exist_ok=True)

    template = """---
title: {title}
enableToc: true
tags:
  - topic/history/decade
type: index
status: complete
future: auto-generated
---

> [!summary] {title}
> > [!summary] Decades
> > 
> > {decade_links}
> 
> 
> > [!summary] Centuries
> > 
> > {century_links}

{events_block}
{people_block}
{stars_block}

# See Also
- [[Encyclopedia Mysenvaria/History/History|History]]
- [[Encyclopedia Mysenvaria/Indexes/History/List of Years|List of Years]]

> [!abstract] [[Meta/Meta|Meta]] || [[Meta/Callouts#Auto-Generated|Auto-Generated Article]]
> This article or a portion of it is auto-generated! If you think there's an error in the generation of this article please file an error through [GitHub issues](https://github.com/RagtimeGal/quartz--encyclopedia-mysenvaria/issues/new/choose)!
"""

    all_decades = range((START_YEAR // 10) * 10, ((END_YEAR // 10) * 10) + 1, 10)
    decade_count = len(all_decades)
    
    for i, dec_start in enumerate(all_decades):
        curr_title = decade_title(dec_start)
        
        # Decade Navigation
        nav = []
        if i > 0:
            t = decade_title(all_decades[i-1])
            nav.append(f"[[{DECADES_DIR_REL}/{t}|{t}]]")
        nav.append(f"**{curr_title}**")
        if i < decade_count - 1:
            t = decade_title(all_decades[i+1])
            nav.append(f"[[{DECADES_DIR_REL}/{t}|{t}]]")
        decade_links = "... " + ", ".join(nav) + " ..."
        
        # Century Navigation Logic
        c_val, c_sfx = get_ordinal_century(dec_start)
        cent_data = []
        
        # Gather neighboring centuries
        for offset in [-1, 0, 1]:
            t_val = c_val + offset
            t_sfx = c_sfx
            
            # Cross the BT/AT boundary if needed
            if t_val < 1:
                t_val = 1
                t_sfx = "AT" if c_sfx == "BT" else "BT"
            
            t_start, t_end = get_century_bounds(t_val, t_sfx)
            
            # Filter by global limits
            if max(t_start, START_YEAR) <= min(t_end, END_YEAR):
                cent_data.append((t_val, t_sfx, t_start))
        
        # Sort chronologically: BT centuries are descending (e.g. 2nd then 1st), AT are ascending
        # We can simply sort by the t_start year
        cent_data.sort(key=lambda x: x[2])
        
        cent_nav = []
        for t_val, t_sfx, _ in cent_data:
            ct = century_title_from_ordinal(t_val, t_sfx)
            link = f"[[{CENTURIES_DIR_REL}/{ct}|{ct}]]"
            cent_nav.append(link)
        
        century_links = "... " + ", ".join(cent_nav) + " ..."

        content = template.format(
            title=curr_title,
            decade_links=decade_links,
            century_links=century_links,
            events_block=render_events(ev_m.get(dec_start, {})),
            people_block=render_people(bi_m.get(dec_start, {}), de_m.get(dec_start, {}), re_m.get(dec_start, {})),
            stars_block=render_stars(st_m.get(dec_start, []))
        )

        if not DRY_RUN:
            (out_dir / f"{curr_title}.md").write_text(content, encoding="utf-8")

if __name__ == "__main__":
    main()