### A PORTION OF, OR ALL OF, THE CODE CONTAINED WITHIN THIS FILE WAS GENERATED BY AN LLM.
import pathlib
import json
from collections import defaultdict
from typing import Dict, List, Any, Tuple, Optional

# --- Configuration Constants ---
START_YEAR = 0  # Adjust based on your timeline requirements
END_YEAR = 2500 # Adjust based on your timeline requirements
DECADES_DIR_REL = "Encyclopedia Mysenvaria/Timeline/Decades"
CENTURIES_DIR_REL = "Encyclopedia Mysenvaria/Timeline/Centuries"
DRY_RUN = False

# --- Helper Functions (Stubs for context) ---
def find_content_root() -> pathlib.Path:
    # Logic to find the root of the wiki/content repository
    return pathlib.Path("./content")

def iter_markdown(root: pathlib.Path):
    return root.rglob("*.md")

def ensure_extracted_json(root: pathlib.Path) -> Dict[str, Any]:
    # Placeholder for the logic that extracts YAML/Frontmatter into a master JSON
    return {}

def wiki_target_from_source(root: pathlib.Path, source: str) -> str:
    # Converts a file path to a wiki-link target
    return source.replace(".md", "").replace("\\", "/")

def wiki_target(root: pathlib.Path, path: pathlib.Path) -> str:
    return str(path.relative_to(root)).replace(".md", "").replace("\\", "/")

def year_suffix(year: int) -> str:
    return f"{year} AC" # Example suffix

def decade_title(start_year: int) -> str:
    return f"The {start_year}s"

def century_title_from_start(start_year: int) -> str:
    return f"{start_year // 100 + 1}th Century"

def decades_dir(root: pathlib.Path) -> pathlib.Path:
    return root / DECADES_DIR_REL

def centuries_dir(root: pathlib.Path) -> pathlib.Path:
    return root / CENTURIES_DIR_REL

def season_day_label(day: Optional[int]) -> Optional[str]:
    if day is None: return None
    # Example logic: 1-90 Spring, 91-180 Summer, etc.
    return f"Day {day}" 

def load_template() -> str:
    return """# {title}
> [!info] Navigation
> {century_links}
> {decade_links}

{events_block}
{people_block}
{stars_block}
"""

def replace_placeholders(template: str, mapping: Dict[str, str]) -> str:
    return template.format(**mapping)

def _alpha_key(s: str) -> str:
    return s.strip().lower()

def _sort_records(records: List[Dict[str, Any]], day_key: str, alpha_key: str):
    """
    Sorts records primarily by day (None last) and secondarily by alpha string.
    """
    def key_func(r):
        d = r.get(day_key)
        a = _alpha_key(r.get(alpha_key, ""))
        # (HasDay, DayValue, Alpha) -> None days sort after integer days
        return (0, d, a) if d is not None else (1, 0, a)
    records.sort(key=key_func)

def _dedupe_records_by_text(records: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    seen = set()
    unique = []
    for r in records:
        txt = r.get("text")
        if txt not in seen:
            unique.append(r)
            seen.add(txt)
    return unique

# ----------------- Data Processing -----------------

def build_events_births_deaths_and_stars(data: Dict[str, Any], root: pathlib.Path):
    events_by_decade = defaultdict(lambda: defaultdict(list))
    births_by_decade = defaultdict(lambda: defaultdict(list))
    deaths_by_decade = defaultdict(lambda: defaultdict(list))
    relationships_by_decade = defaultdict(lambda: defaultdict(list))
    stars_by_decade = defaultdict(list)

    # --- Events ---
    for ev in data.get("event", []):
        sd = ev.get("start_date")
        sdesc = ev.get("start_desc")
        if isinstance(sd, dict) and "year" in sd and isinstance(sdesc, str) and sdesc.strip():
            y = int(sd["year"])
            d = int(sd.get("day", 0)) or None
            dstart = (y // 10) * 10
            sdesc_clean = sdesc.strip()
            events_by_decade[dstart][y].append({
                "day": d,
                "alpha": sdesc_clean,
                "desc": sdesc_clean,
            })

        ed = ev.get("end_date")
        edesc = ev.get("end_desc")
        if isinstance(ed, dict) and "year" in ed and isinstance(edesc, str) and edesc.strip():
            y2 = int(ed["year"])
            d2 = int(ed.get("day", 0)) or None
            dstart2 = (y2 // 10) * 10
            edesc_clean = edesc.strip()
            events_by_decade[dstart2][y2].append({
                "day": d2,
                "alpha": edesc_clean,
                "desc": edesc_clean,
            })

    # --- People ---
    seen_relationship_keys = set()
    for pe in data.get("person", []):
        title = pe.get("title") or pathlib.Path(pe["source"]).stem
        target = wiki_target_from_source(root, pe["source"])

        # Births
        b = pe.get("birth_date")
        if isinstance(b, dict) and "year" in b:
            by = int(b["year"])
            bd = int(b.get("day", 0)) or None
            parts = []
            sd_lbl = season_day_label(bd)
            if sd_lbl: parts.append(sd_lbl)
            parts.append(f"[[{target}|{title}]]")
            d_for_suffix = pe.get("death_date")
            if isinstance(d_for_suffix, dict) and "year" in d_for_suffix:
                parts.append(f"(d. {year_suffix(int(d_for_suffix['year']))})")
            line = ", ".join([parts[0], " ".join(parts[1:])]) if bd else " ".join(parts)
            births_by_decade[(by // 10) * 10][by].append({
                "day": bd, "alpha": title, "text": f"- {line}",
            })

        # Deaths
        d = pe.get("death_date")
        if isinstance(d, dict) and "year" in d:
            dy = int(d["year"])
            dd = int(d.get("day", 0)) or None
            parts = []
            sd_lbl = season_day_label(dd)
            if sd_lbl: parts.append(sd_lbl)
            parts.append(f"[[{target}|{title}]]")
            b_for_suffix = pe.get("birth_date")
            if isinstance(b_for_suffix, dict) and "year" in b_for_suffix:
                parts.append(f"(b. {year_suffix(int(b_for_suffix['year']))})")
            line = ", ".join([parts[0], " ".join(parts[1:])]) if dd else " ".join(parts)
            deaths_by_decade[(dy // 10) * 10][dy].append({
                "day": dd, "alpha": title, "text": f"- {line}",
            })

        # Major Events from People
        if pe.get("major_event", False):
            for date_key, desc_key in [("birth_date", "birth_desc"), ("death_date", "death_desc")]:
                date_val = pe.get(date_key)
                desc_val = (pe.get(desc_key) or "").strip()
                if desc_val and isinstance(date_val, dict) and "year" in date_val:
                    y, day = int(date_val["year"]), (int(date_val.get("day", 0)) or None)
                    events_by_decade[(y // 10) * 10][y].append({
                        "day": day, "alpha": desc_val, "desc": desc_val,
                    })

        # Spouses
        for sp in pe.get("spouses", []) if isinstance(pe.get("spouses"), list) else []:
            partner = sp.get("name")
            sdt, edt = sp.get("start_date"), sp.get("end_date")
            pair = tuple(sorted([title.lower(), str(partner).lower()]))

            # Marriage
            if isinstance(sdt, dict) and "year" in sdt:
                sy, sd = int(sdt["year"]), (int(sdt.get("day", 0)) or None)
                if ("marry", sy, sd, pair) not in seen_relationship_keys:
                    seen_relationship_keys.add(("marry", sy, sd, pair))
                    parts = []
                    sd_label = season_day_label(sd)
                    if sd_label: parts.append(sd_label)
                    parts.append(f"[[{target}|{title}]] marries {partner}")
                    if isinstance(edt, dict) and "year" in edt:
                        parts.append(f"(div. {year_suffix(int(edt['year']))})")
                    line = ", ".join([parts[0], " ".join(parts[1:])]) if sd else " ".join(parts)
                    relationships_by_decade[(sy // 10) * 10][sy].append({
                        "day": sd, "alpha": f"{title} {partner}", "text": f"- {line}",
                    })

            # Divorce
            if isinstance(edt, dict) and "year" in edt:
                ey, ed = int(edt["year"]), (int(edt.get("day", 0)) or None)
                if ("divorce", ey, ed, pair) not in seen_relationship_keys:
                    seen_relationship_keys.add(("divorce", ey, ed, pair))
                    parts = []
                    ed_label = season_day_label(ed)
                    if ed_label: parts.append(ed_label)
                    parts.append(f"[[{target}|{title}]] divorces {partner}")
                    if isinstance(sdt, dict) and "year" in sdt:
                        parts.append(f"(mar. {year_suffix(int(sdt['year']))})")
                    line = ", ".join([parts[0], " ".join(parts[1:])]) if ed else " ".join(parts)
                    relationships_by_decade[(ey // 10) * 10][ey].append({
                        "day": ed, "alpha": f"{title} {partner}", "text": f"- {line}",
                    })

    # --- Stars ---
    star_section = data.get("star", {})
    bases = star_section.get("bases", [])
    pubs = star_section.get("publications", [])
    trns = star_section.get("translations", [])

    for row in (pubs + trns):
        if not row.get("major_event", False): continue
        desc = (row.get("desc") or "").strip()
        if not desc: continue
        y, d = int(row["date"]["year"]), (int(row["date"].get("day", 0)) or None)
        events_by_decade[(y // 10) * 10][y].append({
            "day": d, "alpha": desc, "desc": desc,
        })

    pubs_by_star = defaultdict(list)
    for p in pubs:
        pubs_by_star[(p.get("source", ""), p.get("star_name", ""))].append(p)
    for key in pubs_by_star:
        pubs_by_star[key].sort(key=lambda r: (int(r["date"]["year"]), int(r["date"].get("day", 0))))

    for base in bases:
        key = (base.get("source", ""), base.get("star_name", ""))
        first_pub = pubs_by_star.get(key, [None])[0]
        if not first_pub: continue
        y, d = int(first_pub["date"]["year"]), (int(first_pub["date"].get("day", 0)) or None)
        target = wiki_target_from_source(root, base["source"])
        name = base.get("star_name") or pathlib.Path(base["source"]).stem
        actors = [str(a) for a in first_pub.get("publishers", [])] if isinstance(first_pub.get("publishers"), list) else []
        
        stars_by_decade[(y // 10) * 10].append({
            "year": y, "day": d, "alpha": name,
            "row": {
                "name_link": f"[[{target}|{name}]]",
                "coordinates": base.get("coordinates", ""),
                "date": year_suffix(y), "date_year": y, "date_day": d,
                "actors": ", ".join(actors), "desc": base.get("desc", ""),
            }
        })

    # --- Sorting & Deduping ---
    for d_map in [events_by_decade, births_by_decade, deaths_by_decade, relationships_by_decade]:
        for dec in d_map:
            for yr in d_map[dec]:
                _sort_records(d_map[dec][yr], "day", "alpha")

    for d_map in [births_by_decade, deaths_by_decade, relationships_by_decade]:
        for dec in d_map:
            for yr in d_map[dec]:
                d_map[dec][yr] = _dedupe_records_by_text(d_map[dec][yr])

    def star_sort_key(rec):
        y, d, al = rec.get("year", 0), rec.get("day", None), _alpha_key(rec.get("alpha", ""))
        return (y, 0, d, al) if d is not None else (y, 1, 0, al)
    for dec in stars_by_decade:
        stars_by_decade[dec].sort(key=star_sort_key)

    # Conversion to final output structures
    def sort_year_keys(d): return dict(sorted(d.items()))

    ev_out = {dec: sort_year_keys(yrs) for dec, yrs in events_by_decade.items()}
    b_out = {dec: sort_year_keys({yr: [r["text"] for r in lst] for yr, lst in yrs.items()}) for dec, yrs in births_by_decade.items()}
    d_out = {dec: sort_year_keys({yr: [r["text"] for r in lst] for yr, lst in yrs.items()}) for dec, yrs in deaths_by_decade.items()}
    r_out = {dec: sort_year_keys({yr: [r["text"] for r in lst] for yr, lst in yrs.items()}) for dec, yrs in relationships_by_decade.items()}
    s_out = {dec: [r["row"] for r in rows] for dec, rows in stars_by_decade.items()}

    return ev_out, b_out, d_out, r_out, s_out

# ----------------- Navigation -----------------

def in_range_decade(dec_start: int) -> bool:
    return (START_YEAR // 10) * 10 <= dec_start <= (END_YEAR // 10) * 10

def decade_links_row(root: pathlib.Path, decade_start: int) -> str:
    pieces = []
    for offset in [-10, 0, 10]:
        ds = decade_start + offset
        if in_range_decade(ds):
            name = decade_title(ds)
            if offset == 0: pieces.append(f"**{name}**")
            else:
                target = wiki_target(root, decades_dir(root) / f"{name}.md")
                pieces.append(f"[[{target}|{name}]]")
    return ", ".join(pieces)

def century_links_row(root: pathlib.Path, decade_start: int) -> str:
    cdir = centuries_dir(root)
    cs = (decade_start // 100) * 100
    pieces = []
    for offset in [-100, 0, 100]:
        curr = cs + offset
        name = century_title_from_start(curr)
        p = cdir / f"{name}.md"
        if p.is_file():
            pieces.append(f"[[{wiki_target(root, p)}|{name}]]")
    return ", ".join(pieces)

# ----------------- Renderers -----------------

def render_events_by_year(events_for_decade: Dict[int, List[Dict[str, Any]]]) -> str:
    if not events_for_decade: return ""
    parts = ["# Events"]
    for year, items in events_for_decade.items():
        parts.append(f"## {year_suffix(year)}")
        by_day = defaultdict(list)
        day_order = []
        for rec in items:
            d = rec.get("day")
            if d not in by_day: day_order.append(d)
            by_day[d].append(rec)
        
        for day in day_order:
            rows = by_day[day]
            if day is None:
                for r in rows: parts.append(f"- {r['desc']}")
            else:
                label = season_day_label(day)
                if len(rows) == 1: parts.append(f"- {label} — {rows[0]['desc']}")
                else:
                    parts.append(f"- {label}")
                    for r in rows: parts.append(f"    - {r['desc']}")
    return "\n".join(parts) + "\n"

def render_people_grouped(births, deaths, relations) -> str:
    if not any([births, deaths, relations]): return ""
    parts = ["# Significant People"]
    for title, data in [("Births", births), ("Deaths", deaths), ("Relationships", relations)]:
        if data:
            parts.append(f"## {title}")
            for year, lines in data.items():
                parts.append(f"### {year_suffix(year)}")
                parts.extend(lines)
    return "\n".join(parts) + "\n"

def render_stars_table(rows: List[Dict[str, Any]]) -> str:
    if not rows: return ""
    def esc(s): return str(s or "").replace("|", r"\|")
    header = ("# Stars\n| Name | Coordinates | Date | Publisher(s) | Description |\n"
              "| --- | --- | --- | --- | --- |\n")
    lines = []
    for r in rows:
        dy, dd = r.get("date_year"), r.get("date_day")
        sd = season_day_label(dd) if dd is not None else None
        display_date = f"{sd}, {year_suffix(dy)}" if sd else year_suffix(dy)
        coords = f"({esc(r['coordinates'])})" if r.get('coordinates') else ""
        lines.append(f"| {esc(r['name_link'])} | {coords} | {esc(display_date)} | {esc(r['actors'])} | {esc(r['desc'])} |")
    return header + "\n".join(lines) + "\n"

# ----------------- Execution -----------------

def build_decade_page_content(root, dec, ev, bi, de, re, st) -> str:
    template = load_template()
    e_blk = render_events_by_year(ev)
    p_blk = render_people_grouped(bi, de, re)
    s_blk = render_stars_table(st)
    
    mapping = {
        "title": decade_title(dec),
        "decade_links": decade_links_row(root, dec),
        "century_links": century_links_row(root, dec),
        "events_block": f"\n{e_blk}" if e_blk else "",
        "people_block": f"\n{p_blk}" if p_blk else "",
        "stars_block": f"\n{s_blk}" if s_blk else "",
    }
    return replace_placeholders(template, mapping).rstrip() + "\n"

def main():
    root = find_content_root()
    data = ensure_extracted_json(root)
    ev, bi, de, re, st = build_events_births_deaths_and_stars(data, root)

    ddir = root / DECADES_DIR_REL
    ddir.mkdir(parents=True, exist_ok=True)

    low, high = (START_YEAR // 10) * 10, (END_YEAR // 10) * 10
    for dec in range(low, high + 1, 10):
        content = build_decade_page_content(root, dec, ev.get(dec, {}), bi.get(dec, {}), de.get(dec, {}), re.get(dec, {}), st.get(dec, []))
        out_path = ddir / f"{decade_title(dec)}.md"
        if not DRY_RUN:
            out_path.write_text(content, encoding="utf-8")
            print(f"[WROTE] {out_path}")

if __name__ == "__main__":
    main()