### A PORTION OF, OR ALL OF, THE CODE CONTAINED WITHIN THIS FILE WAS GENERATED BY AN LLM.
import os
import re
import pathlib
import json
from collections import defaultdict
from typing import Any, Dict, List, Optional, Tuple

# ===================== CONFIG =====================
CONTENT_DIRNAME = "content"
METADATA_JSON_REL = "Meta/Programs/debug/metadata_aggregator/extracted_metadata.json"
DRY_RUN = False
EXCLUDE_DIRS = {".git", ".github", ".obsidian", ".quartz", "public", "node_modules", ".vitepress"}

# ----------------- Root discovery -----------------
def find_content_root() -> pathlib.Path:
    curr = pathlib.Path.cwd()
    for _ in range(5):
        if (curr / CONTENT_DIRNAME).is_dir():
            return curr / CONTENT_DIRNAME
        curr = curr.parent
    return pathlib.Path.cwd() / CONTENT_DIRNAME

# ----------------- Metadata Navigation -----------------
def resolve_path(obj: Any, path: str) -> List[Any]:
    parts = [p for p in path.split(".") if p]
    nodes = [obj]
    
    for part in parts:
        next_nodes = []
        is_list_query = part.endswith("[]")
        key = part[:-2] if is_list_query else part
        
        idx_match = re.search(r"\[(\d+)\]$", key)
        forced_idx = int(idx_match.group(1)) if idx_match else None
        if forced_idx is not None: key = key[:key.find("[")]

        for node in nodes:
            if not isinstance(node, dict): continue
            val = node.get(key)
            if val is None: continue
            
            if forced_idx is not None:
                if isinstance(val, list) and 0 <= forced_idx < len(val):
                    next_nodes.append(val[forced_idx])
            elif is_list_query and isinstance(val, list):
                next_nodes.extend(val)
            else:
                next_nodes.append(val)
        nodes = next_nodes
        if not nodes: break

    res = []
    for n in nodes:
        if isinstance(n, list): res.extend(n)
        else: res.append(n)
    return res

# ----------------- Date & Matching Logic -----------------
DATE_RE = re.compile(r"^\s*([+-]?\d+)(?:-([0-9]{1,3}))?\s*$")

def to_float_date(val: Any) -> Optional[float]:
    if isinstance(val, (int, float)): return float(val)
    if isinstance(val, dict):
        # Prefer the internal informal string if available for parsing
        if "informal" in val: val = val["informal"]
        elif "year" in val: return float(val["year"]) + (float(val.get("day", 0) or 0) / 1000.0)
    
    if isinstance(val, str):
        m = DATE_RE.match(val.strip())
        if m:
            return float(m.group(1)) + (float(m.group(2) or 0) / 1000.0)
    return None

def check_date_rule(val: Any, criteria: Dict[str, Any]) -> bool:
    v = to_float_date(val)
    if v is None: return False
    for op, threshold in criteria.items():
        thr = to_float_date(threshold)
        if thr is None: continue
        if op == "gt" and not (v > thr): return False
        if op == "lt" and not (v < thr): return False
        if op == "gte" and not (v >= thr): return False
        if op == "lte" and not (v <= thr): return False
    return True

def matches_rule_item(fm: Dict[str, Any], rule_item: Any) -> bool:
    if isinstance(rule_item, str):
        return any(v is not None and str(v).strip() != "" for v in resolve_path(fm, rule_item))
    if not isinstance(rule_item, dict): return False
    
    for path, expected in rule_item.items():
        vals = resolve_path(fm, path)
        if isinstance(expected, dict):
            if "exists" in expected:
                if bool(expected["exists"]) != any(vals): return False
                continue
            if "date" in path.lower() or any(k in expected for k in ["gt", "lt", "gte", "lte"]):
                if not any(check_date_rule(v, expected) for v in vals): return False
                continue
        
        match = False
        for v in vals:
            v_str = str(v)
            if isinstance(expected, list):
                for e in expected:
                    e_str = str(e)
                    if e_str.endswith('*') and v_str.startswith(e_str[:-1]): match = True; break
                    elif v_str == e_str: match = True; break
                if match: break
            else:
                e_str = str(expected)
                if e_str.endswith('*') and v_str.startswith(e_str[:-1]): match = True; break
                elif v_str == e_str: match = True; break
        if not match: return False
    return True

# ----------------- Sorting & Rendering -----------------
def get_sort_key(page: Dict[str, Any], by: str, method: str):
    vals = resolve_path(page["metadata"], by)
    raw = vals[0] if vals else ""
    is_date = "date" in by.lower()
    
    if not raw: return (1, "")
    val = to_float_date(raw) if is_date else str(raw)
    if "natural" in method and isinstance(val, str):
        return (0, [int(c) if c.isdigit() else c.lower() for c in re.split(r"(\d+)", val)])
    return (0, val)

def render_block(pages: List[Dict[str, Any]], sort_spec: List[Dict], h_level: int) -> List[str]:
    if not pages: return []
    
    current_pages = list(pages)
    for spec in reversed(sort_spec):
        by = spec.get("by", "title")
        method = spec.get("method", "standard_forward")
        current_pages.sort(key=lambda p: get_sort_key(p, by, method), reverse="backward" in method)

    def group_pages(pgs: List[Dict], spec_idx: int, level: int) -> List[str]:
        if spec_idx >= len(sort_spec):
            return [f"- {p['metadata']['link']}" for p in pgs]
            
        spec = sort_spec[spec_idx]
        sh = spec.get("subheaders", {})
        if not sh.get("generate"):
            return group_pages(pgs, spec_idx + 1, level)
            
        by = spec.get("by", "title")
        method = sh.get("method", "value")
        fmt = sh.get("format", "{value}")
        
        groups = defaultdict(list)
        keys = []
        for p in pgs:
            raw = (resolve_path(p["metadata"], by) or [""])[0]
            label = "Other"
            if raw:
                if method == "first_character": label = str(raw)[0].upper()
                elif method.startswith("floor_"):
                    step = int(method.split("_")[1])
                    v = to_float_date(raw)
                    label = str(int((v // step) * step)) if v is not None else "Other"
                else: label = str(raw)
            if label not in groups: keys.append(label)
            groups[label].append(p)
            
        output = []
        for k in keys:
            output.append(f"{'#' * min(level+1, 6)} {fmt.replace('{value}', k)}")
            output.extend(group_pages(groups[k], spec_idx + 1, level + 1))
        return output

    return group_pages(current_pages, 0, h_level) + [""]

def main():
    root = find_content_root()
    json_path = root / METADATA_JSON_REL
    if not json_path.exists():
        print(f"Error: Aggregated metadata not found at {json_path}")
        return

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    all_items = data.get("pages", [])
    # Index pages are specifically those that have an 'index' key in their metadata
    index_pages = [p for p in all_items if "index" in p["metadata"] and isinstance(p["metadata"]["index"], list)]
    
    wrote = 0
    for idx_page in index_pages:
        rel_path = idx_page.get("parent") or idx_page.get("src_rel")
        # Ensure we only try to write to actual files, not subpage virtual paths
        actual_file_path = root / rel_path.split("::")[0]
        
        if not actual_file_path.exists(): continue
        
        try:
            content = actual_file_path.read_text(encoding="utf-8")
            lines = content.splitlines()
        except Exception: continue

        changed = False
        for config in idx_page["metadata"]["index"]:
            h_name = config.get("header_name")
            if not h_name: continue
            
            span = None
            for i, ln in enumerate(lines):
                m = re.match(r"^(#{1,6})\s+(.*?)\s*$", ln)
                if m and m.group(2).strip() == h_name:
                    lvl = len(m.group(1))
                    start, end = i + 1, len(lines)
                    for j in range(start, len(lines)):
                        if lines[j].startswith("> [!") or (re.match(r"^#{1,6}\s", lines[j]) and len(re.match(r"^(#{1,6})", lines[j]).group(1)) <= lvl):
                            end = j; break
                    span = (i, start, end, lvl)
                    break
            
            if not span: continue
            _, r_start, r_end, h_lvl = span
            
            inc = config.get("included_data", [])
            if isinstance(inc, dict): inc = [inc]
            exc = config.get("excluded_data", [])
            if isinstance(exc, dict): exc = [exc]
            
            matched = [
                p for p in all_items 
                if all(matches_rule_item(p["metadata"], r) for r in inc)
                and not any(matches_rule_item(p["metadata"], r) for r in exc)
            ]
            
            new_content = render_block(matched, config.get("sort", []), h_lvl)
            if lines[r_start:r_end] != new_content:
                lines[r_start:r_end] = new_content
                changed = True
        
        if changed:
            if not DRY_RUN:
                actual_file_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
                print(f"[UPDATED] {actual_file_path.name}")
                wrote += 1
            else:
                print(f"[DRY-RUN] Would update {actual_file_path.name}")

    print(f"Done. Processed {len(all_items)} entries, updated {wrote} indexes.")

if __name__ == "__main__":
    main()